### ISSUE TITLE
mklink don't work in Greasemonkey 3.5

### ISSUE THREAD

**Issue by miaolapd** [greasemonkey/greasemonkey#2310] opened 2015-10-26 05:24 UTC
I use mklink for developing script on windows.
For example，`mklink "C:\Users\xxx\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxx.default\gm_scripts\myscript\test.user.js" "D:\Project\myscript\test.user.js"`
But when I upgrade to 3.5, the script don't work any more. And I don't use mklink, use the original script file, it can work normally.
And I try to reinstall 3.4.1, the script (via mklink) can work again.
I hope this issue can be solved, thanks!

**Comment by janekptacijarabaci** [comment] 2015-10-26 05:37
Dupe of #2305

**Closed** 2015-10-26 13:09 UTC
