### ISSUE TITLE
Javascript Exceptions in Firebug and FF Browser Console

### ISSUE THREAD

**Issue by subz87** [greasemonkey/greasemonkey#2117] opened 2015-03-18 23:38 UTC
Firefox 36.0.1
Firebug 2.0.8
Greasemonkey 3.0

When exceptions are NOT caught they only appear in FF browser console but not in Firebug.  Although if I throw and catch an exception, report it with `console.error` it's reported in both the browser console and Firebug.

![exceptiontest](https://cloud.githubusercontent.com/assets/11546815/6721509/b67b9a14-cdc5-11e4-860b-5758b8395636.png)

It's not a critical problem, but I thought I'd report it here in case you can share more information about why this happens and whether it's anything related to GM that can be fixed.

``` javascript
// ==UserScript==
// @name        exception test
// @namespace   ecofriend
// @include     https://greasyfork.org/de/forum/discussion/*
// @version     1
// @grant       none
// ==/UserScript==

console.log('exception reporting - without try catch;');

// exceptions outside try catch are reported in the browser console (not Firebug)
throw new Error('food bar');
//throw new TypeError('food bar');

try {
//  throw new Error('food bar');
//  throw new TypeError('food bar');
}
catch(exception) {
    console.error(exception);
}
```

**Comment by jerone** [comment] 2015-03-19 08:22
Did you have both open at the same time? I heard somewhere that `console` is only caught by one develop tool at the same time.

**Comment by tobbexiv** [comment] 2015-03-19 09:36
If you have the Web Console and Firebug, yes. But the Browser Console is independent. I was able to reproduce it also with only one console opened.

**Comment by subz87** [comment] 2015-03-19 13:15
@tobbexiv your response got me thinking.  In Firefox I tried both Web and Browser Consoles, open at the same time across a selection of web pages.  Exceptions from everywhere are reported in the Browser Console but not the Web Console.  So it seems that Firebug and the Web Console are displaying the same logging information, from all sources; userscripts, add-ons and web javascript.

So I'm going to guess that this is being addressed with Firebug 3 and it's not a specific issue with Greasemonkey.

**Comment by spiralx** [comment] 2015-04-25 15:29
All of the output from `console.log`, `console.info`, etc., along with any warnings or errors generated by a user script, only go to the Browser Console and not the Web Console, and it's been that way since the Browser Console was added I think - certainly it's been a good couple of years since the errors showed up in the Web Console or Firebug. It's pretty annoying actually, as it makes missing problems very easy :(

**Comment by janekptacijarabaci** [comment] 2015-05-24 18:52
I've pushed a fix to the testing branch: https://github.com/greasemonkey/greasemonkey/compare/master...janekptacijarabaci:_testBranch_console_web

It's still not reliable (GM_log, GM_log - e10s on). I haven't a better solution (now).

See also: https://github.com/greasemonkey/greasemonkey/issues/1809

**Comment by PotcFdk** [comment] 2015-07-15 21:11
As you can see in the issue referenced above, I have a similar problem.
However, for me, it doesn't even show exceptions in the normal web console.

**Comment by janekptacijarabaci** [comment] 2015-07-16 06:20
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1136995#c5
_"...we are going to remove content messages from the browser console anyway"_

**Closed** 2017-07-25 13:56 UTC
