### ISSUE TITLE
Firefox Developer

### ISSUE THREAD

**Issue by Naufrage** [greasemonkey/greasemonkey#2329] opened 2015-11-08 13:15 UTC
Firefox developer, I can not edit script. Right-click the name of the script does not work and when I go to the settings, even if I choose the option "Edit this script", nothing happens

**Comment by janekptacijarabaci** [comment] 2015-11-08 13:51
Dupe of https://github.com/greasemonkey/greasemonkey/issues/2304 ?
Does new Beta GM fix this? (3.6beta1)

**Comment by Naufrage** [comment] 2015-11-08 15:21
Yep, thank's

**Closed** 2015-11-09 17:55 UTC
