### ISSUE TITLE
Tabs opened from about:blank causes Firebug to stay opened

### ISSUE THREAD

**Issue by klenium** [greasemonkey/greasemonkey#2212] opened 2015-06-28 15:28 UTC
```
// ==UserScript==
// @name newtab
// @include about:blank
// ==/UserScript==
document.body.innerHTML = '<a href="http://google.hu/" target="_blank">Click!</a>';
```
1. Open Google from about:newtab.
2. Press F12. OK, Firebug is opened.
3. Press F12. OK, Firebug is now closed.
4. Switch to another tab.
5. Switch back to Google. Firebug is opened, when it should be closed.

When I press Ctrl+T and type google.com, or disable Greasemonkey and open Google from the Firefox's default newtab, Firebug stays closed.

**Comment by dogancelik** [comment] 2015-07-09 17:13
You need to press Shift+F12 to close Firebug. F12 hides Firebug, doesn't close it.

**Comment by janekptacijarabaci** [comment] 2015-08-23 08:21
Not confirmed on:
GM 3.4beta1
Firebug 2.0.11
Firefox 40.0.2 and 43.0a1 (2015-08-22) - e10s: off (e10s: on - Firebug: stable version don't work)

**Comment by klenium** [comment] 2015-08-23 09:40
It works for me too right now. As I remember I used Firefox 39 and GM 3.1, Firebug ~2

**Comment by klenium** [comment] 2015-08-23 10:24
Try the same steps ablove, but instead of minimizing, close Firebug.

**Comment by janekptacijarabaci** [comment] 2015-08-23 10:50
Not confirmed on:
GM 3.1
Firebug 2.0 (and 2.0.11)
Firefox 39.0

Try it on a new profile where there are no addons except Firebug/Greasemonkey (disable every addon you have except Firebug/Greasemonkey).

**Comment by klenium** [comment] 2015-08-23 11:48
https://youtu.be/2o5JSxrx8z4
Firefox 40.0.2 Firebug 2.0.11 Greasemonkey 3.3

**Comment by janekptacijarabaci** [comment] 2015-08-23 12:18
Oh, I see it.

Unfortunately, I don't get it that way:
1. about:blank, Firebug is opened.
2. Open Google from about:blank. 
3. Press F12. OK, Firebug is now closed.
4. Switch back to about:blank. Firebug is opened, when it should be closed.

Well, that's okay :-)

**Comment by janekptacijarabaci** [comment] 2015-08-23 13:20
But, this has nothing to do with Greasemonkey...

Greasemonkey uninstalled. And:

When you add the element:
```<a href="http://google.hu/" target="_blank">Click!</a>```
to about:blank page (manipulation of DOM objects using Firebug / Web console), the problem remains unsolved.

**Comment by dogancelik** [comment] 2015-08-23 17:25
@klenium When you press F12, Firebug opens, when you press it again, it minimizes.

If you really want to close Firebug, press Shift + F12. This is not a bug.

**Closed** 2015-09-23 16:22 UTC
Labels: worksforme
