### ISSUE TITLE
UI Window too large for my screen

### ISSUE THREAD

**Issue by shoaibshakeel381** [greasemonkey/greasemonkey#2222] opened 2015-07-20 13:04 UTC
When I try to edit my scripts the window is too large for me to access 'Edit this User Script' button/ I think attached screenshot says it all. BTW my resolution is 1366 X 768 (Normal for Laptops). ![screenshot 4](https://cloud.githubusercontent.com/assets/1955721/8776285/50a56666-2f09-11e5-82c0-d7fe0090b9b6.png)

**Comment by arantius** [comment] 2015-07-20 13:05
Dupe of #2191 .

Try 3.3beta2: https://addons.mozilla.org/firefox/downloads/file/329720/greasemonkey-3.3beta2-fx.xpi

**Closed by arantius** 2015-07-20 13:05 UTC
