### ISSUE TITLE
GM_addStyle not work when run at document start

### ISSUE THREAD

**Issue by tiansh** [greasemonkey/greasemonkey#2545] opened 2017-08-16 06:42 UTC
```javascript
// ==UserScript==
// @name        test
// @namespace   https://github.com/tiansh/
// @description test
// @include     http://example.com/*
// @version     1
// @grant       GM_addStyle
// @run-at      document-start
// ==/UserScript==

alert(GM_addStyle('* { color: red !important; }'));
```

got null instead of the <style> tag, and also no styles applied.

GM 3.11
Fx 56.0b2 (55 not tested, but users reported me it wont wonk on 55 either)
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by janekptacijarabaci** [comment] 2017-08-16 08:29
Dupe of #2515

**Closed** 2017-08-16 08:32 UTC
