### ISSUE TITLE
Pale Moon 27.0.3 cannot edit scripts

### ISSUE THREAD

**Issue by zootboy** [greasemonkey/greasemonkey#2478] opened 2017-02-07 21:59 UTC
Running Pale Moon 27.0.3 on Linux, Greasemonkey 3.9. I get the following error when I try to edit a script:

Error: TypeError: GM_util.openInEditor is not a function
Source File: chrome://greasemonkey/content/addons4-overlay.js
Line: 165

Trying the same action in Firefox 51 on the same machine successfully opens the editor window.

**Comment by janekptacijarabaci** [comment] 2017-02-08 03:23
Dupe of #2456

**Closed** 2017-07-25 14:02 UTC
