### ISSUE TITLE
Pages will hang/not load on latest Waterfox and Firefox Developer edition

### ISSUE THREAD

**Issue by madmuffinz** [greasemonkey/greasemonkey#2608] opened 2017-10-06 00:33 UTC
An example would be this script
https://greasyfork.org/en/scripts/2312-resize-image-on-open-image-in-new-tab

It's not the script because when using Tampermonkey, everything works correctly.
Also using my older version of Firefox with Greasemonkey ver 3.11 works as inteded too.
I made my discoveries about this bug here: https://greasyfork.org/en/forum/discussion/29945/
"This works fine for me on Firefox (43) with Greasemonkey, but I am moving onto Waterfox (using v55 at the moment) with Greasemonkey, sometimes the links work but oddly sometimes a page is completely white when opening a link from a page, even if I refresh the page or manually input the url!

I have to disable the script, refresh, and the page will then load. It's crazy, and I can't really tell what's going on but it is definitely with the script.
I also tried this with a fresh profile with the browser and the script only, but it still did not work.
Could it be Greasemonkey?

I tried using the script with Tampermonkey, and it works fine on that, but I am trying to stick with Greasemonkey

Update:
Keeping the script disabled on a image url that will be redirected by the script will load, enabling it and refreshing the page will redirect me, but the image will not resize. It will stay the same size from the previous url"

**Comment by Sxderp** [comment] 2017-10-06 14:03
Duplicate of #2524

**Closed** 2017-10-09 17:29 UTC
Labels: duplicate
