### ISSUE TITLE
[Q] How I can run custom script in about:newtab?

### ISSUE THREAD

**Issue by dehghani-mehdi** [greasemonkey/greasemonkey#2450] opened 2016-11-20 10:29 UTC
Hi,

I'm using `Firefox Developer Edition v52.x`, also I just installed `Greasemonkey` (_I used Greasemonkey before_), I tired to run simple script when I open `newtab`, but doesn't work.

Here is the script file's content:

    // ==UserScript==
    // @name        Newtab
    // @namespace   Test
    // @include     about:newtab
    // @version     1
    // @grant       none
    // ==/UserScript==

    alert('Hello from Greasemonkey!');

Is something wrong in my code? or I missed something?

Thank you!

**Comment by janekptacijarabaci** [comment] 2016-11-20 11:26
about:newtab has chrome privileges.

Dupe of #1791

**Closed** 2017-02-24 15:43 UTC
Labels: wontfix

**Comment by Aldekein** [comment] 2025-09-11 15:29
> about:newtab has chrome privileges.

Could I ask what does it mean? I tried `@include     about:newtab` and just nothing happens, code doesn't run. 
The other thread (https://github.com/greasemonkey/greasemonkey/issues/1791) is just closed with no answers at all.

**Comment by arantius** [comment] 2025-09-11 15:36
https://wiki.greasespot.net/Include_and_exclude_rules#Greaseable_schemes
