### ISSUE TITLE
Installation: Detect user scripts using the URL *path*

### ISSUE THREAD

**Issue by ulrichb** [greasemonkey/greasemonkey#2403] opened 2016-06-17 13:40 UTC
At the moment, Greasemonkey [uses the whole URL](https://github.com/greasemonkey/greasemonkey/blob/2a2ef526d3840a87374c2057ca3a65729780ca36/modules/installPolicy.js#L76) (including the query string) to detect user scripts to offer the install dialog.

This is a problem when hosting user scripts in locations which require additional query strings after the path (e.g. `/a/b/my.user.js?version=x`).

Tampermonkey uses the URL _path_, which works in this scenario. Please support this too.

To avoid a breaking change the best would be to check both, the complete URL and the URL path.

**Comment by janekptacijarabaci** [comment] 2016-06-17 13:51
Dupe of https://github.com/greasemonkey/greasemonkey/issues/2130

**Closed** 2016-06-17 14:04 UTC
