### ISSUE TITLE
GM fails to detect user scripts if the URL has a query string.

### ISSUE THREAD

**Issue by davmillar** [greasemonkey/greasemonkey#2931] opened 2018-04-02 16:20 UTC
If the URL has a query string, Greasemonkey fails to detect it as a user script.

*Use case:*
Our team has some user scripts for working within our internal applications that we update periodically. We use Confluence to store the documentation and the userscript. Confluence automatically updates the link when a new version is made, but it does so by adding a query string for the version number of the file that is newest, e.g. https://localhost:8001/foo.user.js?version=4&apiversion=2

**Comment by Eselce** [comment] 2018-04-02 19:46
I just tested to load files like `https://.../script.user.js?version=1&s=0`, and the install dialog appeared...

**Comment by arantius** [comment] 2018-04-02 20:26
It's always been this way.  See #2130 and #1683 .

**Comment by makyen** [comment] 2019-03-19 18:50
This is caused by the Match Pattern Array in user-script-detect.run.js, which is used when adding the `webRequest.onHeadersReceived` listener, containing only `'*://*/*.user.js'`. Contrary to the Match Pattern calling the [last portion of the Match Pattern the "path"](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#path)<sup>1</sup>, it actually matches against the URL path and URL query string.

This can be resolved by changing:

    {'urls': ['*://*/*.user.js'], 'types': ['main_frame']},

to

    {'urls': ['*://*/*.user.js', '*://*/*.user.js?*'], 'types': ['main_frame']},

in src/bg/user-script-detect.run.js. Adding the second entry in the Match Pattern Array matches all URLs where the URL path ends in `.user.js`, but which have a query string.

----
1. The Match Pattern documentation calling that portion "path" is, unfortunately, confusing (legacy from Chrome documentation). I've updated the Match Pattern page to be more explicit about what is being matched against.

**Comment by makyen** [comment] 2019-03-19 18:59
I encountered this when attempting to load a userscript from a GitHub private repository. While the original URL for the userscript contains no query string, GitHub redirects that URL to one that contains a `?token=`. This prevents Greasemonkey from installing from GitHub private repositories.

TM, on the other hand, has no trouble doing so. I did not test to see if TM stumbles over there being a query string when the original URL contains one. For the GitHub private repository URLs, TM detects the first `webRequest`, prior to the redirect. Thus, its detection of userscript URLs doesn't see a URL with query string.

**Comment by Cerberus-tm** [comment] 2019-03-19 20:17
@makyen Just to be sure, are you sure the question mark isn't a special sign like the asterisk, in whatever method ised used for wildcards?

Secondly, what if there are two question marks in a url? In a normal url, I believe the second one will be part of the query string and is taken like a literal question mark.

**Comment by makyen** [comment] 2019-03-19 21:30
@Cerberus-tm  Yes, the `?` has no special meaning in [Match Patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns). Unlike regexes or globs, the only special character is `*`, and the special string `<all_urls>`.

[HTML5 requires an additional `?` to be percent encoded](https://en.wikipedia.org/wiki/Query_string#URL_encoding).<sup>1</sup> If, for some reason, it wasn't, then in the specific case that you describe, it would still match. The second `*` would match the subsequent `?`. It matches anything. The added Match Pattern is only looking for a `?` immediately following the `.user.js`, which, in the vast majority of cases, will indicate that there is a URL path that ends with `.user.js` followed by a query string. However, if for some reason the additional `?` was not percent-encoded, then there would be the possibility of erroneous matches, but that would require  `.user.js?` to be somewhere in the query string.

Unfortunately, Match Patterns are quite limited. There are URLs which are already misidentified based on the the existing first Match Pattern. In fact, [the workaround](https://github.com/greasemonkey/greasemonkey/issues/2130#issuecomment-86998208) for getting GM to recognize a script that it currently does not is to add an additional fake parameter to the query string so the URL ends with `.user.js`.

The only way to be sure would be to add additional logic to test the URL in the `webRequest.onHeadersReceived` to see if it really matches the desired pattern. In fact, that's what's intended. The Match Patterns are intended to be simple matches that are a first round of elimination for what's being watched. The goal, from the browser's POV, is to spend as little time on an extension's match as possible when it does not match. This is primarily done by making the first test for matching quite simple, in order to eliminate the significant majority of URLs from further consideration.


----
1. I'd need to re-read the spec to verify where it's all restricted. The specific HTML5 spec. section referenced by the linked Wikipedia page is for `<form>` submission. So, it's likely to be percent-encoded in the significant majority of cases, but I'm unsure if all cases are covered. I don't think that they are.

**Comment by Cerberus-tm** [comment] 2019-03-19 21:38
@makyen Ah, that all makes sense.
Being able to install scripts from additional (trustworthy) sites would be nice.

**Comment by mendhak** [comment] 2020-04-19 13:56
An additional use case is installing GreaseMonkey scripts from private Github repos. In private repos, when viewing the 'Raw' of a file, Github appends a `?token=xxx` to the URL, so GreaseMonkey doesn't pick up on it. 

It would be great if [this PR could be reviewed](https://github.com/greasemonkey/greasemonkey/pull/3026) as it would allow querystring params.

**Comment by Eselce** [comment] 2020-08-23 23:40
Thank you for the answer, you are right, forms are not exactly links, only the action is.
(This may explain, why Firefox changed its behaviour to sth. similar to `Chrome`, `Opera` or `Edge`.)
A form was an easy possibility to create an Install button, submitting with no parameters.
(Sample overview page is [https://eselce.github.io/OS2.scripts/](https://eselce.github.io/OS2.scripts/))

I hate to say it, but Tampermonkey and Violentmonkey acknowledge this.
I don't want to lose even more users to other script managers.

Two of the most annoying obstacles for everyday users are now occurring only with `Greasemonkey`:
- The source code is shown to them without installation. They need to delete the `?` in the URL input line.
- They have to open pages in new windows because of the "executing in frame" bug.

This is so sad, I would like them to use `Greasemonkey`, but how can I recommend that, if they get problems?

**Comment by eight04** [comment] 2020-08-25 10:12
This will allow users to host their script on more sites e.g. dropbox that generate links containing query.

**Closed** 2023-11-02 14:00 UTC
Labels: bankruptcy
