### ISSUE TITLE
"Show Script Source" doesn't work

### ISSUE THREAD

**Issue by fireattack** [greasemonkey/greasemonkey#2238] opened 2015-08-16 10:41 UTC
Test user.js: https://greasyfork.org/scripts/268-append-tag-searching-tub/code/Append%20Tag%20Searching%20Tub.user.js

If you click it, it will show "Greasemonkey Installation" and there is a "Show Script Source" button. But if you click that, it will just pop another Installation dialog (but notice this time the JS location bacame a Local/Temp one) and again and again... I can never get a script source view.

![abc](https://cloud.githubusercontent.com/assets/4130991/9292940/7a2b6802-43d9-11e5-9054-83791b10737a.gif)

**Comment by janekptacijarabaci** [comment] 2015-08-16 10:55
Dupe of https://github.com/greasemonkey/greasemonkey/issues/2202

**Closed** 2015-08-16 13:36 UTC
Labels: duplicate
