### ISSUE TITLE
Version 3.13 prevents Firefox from shutting down

### ISSUE THREAD

**Issue by Khris777** [greasemonkey/greasemonkey#2579] opened 2017-09-23 05:33 UTC
Today I started experiencing weird crash reports from Firefox after I closed it, they were saying that Firefox took too long to shut down.

It turned out the Firefox process wasn't shutting down anymore after closing the program.

After activating and deactivating my addons I found the issue only happend when Greasemonkey was activated and disappeared after deactivating it. If userscripts are active or inactive does not matter.
I tested with having all Addons but Greasemonkey deactivated and the problem persisted.

My system:
Windows 7 64bit
Firefox 55.0.3

**Comment by PHIL-IP** [comment] 2017-09-23 06:17
Hi,
same things for me under Windows 10 and FF 55.0.3
To solve the problem I must disable Greasemonkey in the extensions list.

**Comment by jerone** [comment] 2017-09-23 10:27
Confirmed!
Restarting FF doesn't work anymore; it idles with minimal memory forever.
With GM disabled, FF cleanly restarts again.

_Windows 10 64-bit_
_FF 55.0.3 64-bit_
_GM 3.13_

**Comment by jerone** [comment] 2017-09-23 10:35
Duplicate of https://github.com/greasemonkey/greasemonkey/issues/2573

**Comment by vanowm** [comment] 2017-09-23 18:26
v3.13 prevents Waterfox 55.0.2 from starting at all on one of my profiles. It shows in task manager as browser started, but no window shows.
The amount of changes between v3.12 and 3.13 just doesn't make sense why this issue even happening...

**Comment by jerone** [comment] 2017-09-23 18:32
The issue appeared in 3.11. See https://github.com/greasemonkey/greasemonkey/issues/2573 for more details.

**Closed** 2017-09-23 21:14 UTC
