### ISSUE TITLE
lots of userscripts no longer working with firefox niglhly 44 and greasemonkey 3.5

### ISSUE THREAD

**Issue by ale82to** [greasemonkey/greasemonkey#2325] opened 2015-11-04 23:09 UTC
this userscript 
even this userscript is no longer working with greasemonkey 3.5
https://greasyfork.org/en/scripts/9525-focus-input-text-field-on-esc
is no longer working with greasemonkey 3,5 or 3.6 beta
firefox 44 nighly on osx with es 10 enabled
disabling es 10 solves the issue.

**Comment by ngyikp** [comment] 2015-11-08 15:41
Also having the same issue with Greasemonkey 3.5 on nightly 45.0a1 (2015-11-08) on Mac OS with e10s on, using aurora 44.0a2 or disabling e10s fixes the issue, and Windows XP is not affected.

Browser Console reports this strange error:
```
Error opening input stream (invalid filename?): file:///Users/ngyikp/Library/Application%20Support/Firefox/Profiles/b9teiub7.default/gm_scripts/nightly_with_e10s_test/test.user.js
```
even though the file is indeed there.

Test script is super bare-bones, can't be anything wrong with it:
```js
// ==UserScript==
// @name        nightly with e10s test
// @namespace   ngyikp
// @version     1.0
// @include http://example.com/*
// ==/UserScript==

alert('hi');
```

**Comment by janekptacijarabaci** [comment] 2015-11-08 15:53
@ngyikp

At least for you:
Dupe of #2296

**Comment by arantius** [comment] 2016-01-20 17:06
Definitely dupe as mentioned.

**Closed by arantius** 2016-01-20 17:06 UTC
