### ISSUE TITLE
Changing 'grant none' to 'grant GM_addStyle' doesn't grant this API method

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2316] opened 2015-10-28 00:49 UTC
To reproduce (in FF Nightly 2015-10-27 x64 with GM 3.5):

- install this script:
```
// ==UserScript==`
// @name        test
// @include     *
// @grant       none
// ==/UserScript==

GM_addStyle("body {background-color: yellow !important;}");
```
- Try to run it on any page: 
nothing happens (as expected). 
Now change `// @grant none` into `// @grant       GM_addStyle` and run script again: 
it still doesn't work (i.e. you still get `GM_addStyle is not defined` in Browser Console).

The only way to make it work is to uninstall and re-install it.

<br/>
Confirmed on:
Firefox 44.0a1 Nightly x64 (2015-10-27) (e10s: on/off)
Firefox 44.0a1 Nightly (2015-10-27) (e10s: on/off)

Not confirmed on:
Firefox 43.0a2 Developer Edition (2015-10-27)
Firefox 42 beta

**Comment by janekptacijarabaci** [comment] 2015-10-28 05:48
Dupe of #2311

**Closed** 2015-10-28 22:16 UTC
