### ISSUE TITLE
Update CodeMirror

### ISSUE THREAD

**Issue by tranzitwww** [greasemonkey/greasemonkey#2894] opened 2018-03-04 12:44 UTC
Hi, Since the old ways the exporting scripts are gone, there seems to be another issue when someone tries to copy text from Greasemonkey editor window.
Evan editing it there is complicated, because, if I want to move a block of lines or a bigger function with cut&paste is not possible
Now it allows me to copy just a part of the code (more exactly 1055 characters), but never the whole thing.
Trying to do a CRTL+A and CRTL+C for a script larger than 1055 characters will results in having a clipboard with just one character "-" (minus).
It always fill the clipboard "-" for when trying to copy a larger text code, and this is frustrating because I just want to edit my own scripts and not to steal code from others (if is a security/privacy/copyright stuff)

I'm using Firefox 58 and Greasemonkey 4.2
Thanks!

**Comment by Eselce** [comment] 2018-03-04 13:01
Just copied 271.323 bytes from a script by using Ctrl-A Ctrl-C without a problem (Win 8.1)...

**Comment by tranzitwww** [comment] 2018-03-04 13:43
I have Win7 64bit, but defensively that is not the cause...
Is there any other way to "extract" the script code from the editor or from firefox?

#2814 Doesn't include any export button...

**Comment by Eselce** [comment] 2018-03-04 14:05
Just wondered, because I never experienced any size limit.

In future, you can expect #2747 to help you. For now? I just wonder...

**Comment by tranzitwww** [comment] 2018-03-04 14:30
For sure, it will be nice to have a way to backup or export the script,
I saw that before posting this, but Copy/Paste was no included :)

**Comment by Sxderp** [comment] 2018-03-04 14:32
I think it's a code mirror thing. If I remember correctly the hidden text field it uses doesn't always have all the text in it. 

Might be and add-on or something that could help.

**Comment by tranzitwww** [comment] 2018-03-04 14:42
I experienced that to when I've tried to save the GM editor as a HTML page (or txt) from Firefox "Save Page as".
It just saves few lines, and everything that is bellow the screen (in the scroll bar) are missing.
But with copy/paste is different. If I exceed the 1055 bytes even if I select one more character from the the same line, not going any line below it will replace the clipboard with that "-" minus sign

**Comment by Sxderp** [comment] 2018-03-04 15:46
It's a codemirror issue. I can find reports going back to years mentioning this odd behavior. 

According to https://github.com/openstyles/stylus/issues/225 the issue is resolved in 5.27.0+. We currently have 5.25.0 in our repo. An update may be what's required.

**Comment by tranzitwww** [comment] 2018-03-04 16:05
Thanks Sxderp!
It was related to that HTML object "Textarea" with its makeup scripts (codemirror)
Anyway a export/download button next to save wouldn't hurt :)

**Comment by Sxderp** [comment] 2018-03-25 22:17
I think @arantius should do this. Mostly because it's part of a third-party library and I assume when submitting to AMO he needs to provide links to exact versions and whatnot.

**Comment by arantius** [comment] 2018-03-28 16:50
09d1fe4905f037924261f1defbd4dea9834731a1

**Closed by arantius** 2018-03-28 16:50 UTC
