### ISSUE TITLE
TypeError: Services.locale.getLocaleComponentForUserAgent is not a function

### ISSUE THREAD

**Issue by andrykyt** [greasemonkey/greasemonkey#2492] opened 2017-03-31 12:43 UTC
on firefox 55.0a1 (2017-03-30) startup, errors below is shown up.  Add-on Manager does not list installed scripts, and scripts does not work.

> Failed to load module chrome://greasemonkey-modules/content/util/getPreferredLocale.js.  XPCOMUtils.jsm:279
> TypeError: Services.locale.getLocaleComponentForUserAgent is not a function  getPreferredLocale.js:10:12

**Comment by janekptacijarabaci** [comment] 2017-03-31 12:50
Dupe of #2488 ( #2489 ).

**Closed** 2017-03-31 13:09 UTC
Labels: duplicate

**Comment by arantius** [comment] 2017-04-25 02:02
I've just pushed version 3.11beta1: https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta?page=1#version-3.11beta1

It would be very useful if you could install it and confirm that it fixes this issue.

**Comment by andrykyt** [comment] 2017-05-15 08:55
3.11 beta1 working well for a while.  thank you for fixing!
