### ISSUE TITLE
Error output is useless as far as what line an issue is on

### ISSUE THREAD

**Issue by DoomTay** [greasemonkey/greasemonkey#2731] opened 2017-11-28 05:07 UTC
A simple error in a script

```javascript
// ==UserScript==
// @name        Internal script issue
// @require     https://cdn.rawgit.com/pnitsch/BitmapData.js/ddb2205fb44a7b02725288f30db34a0dd433d6eb/js/Point.js
// @version     1.0.0
// @grant       none
// ==/UserScript==

var point1 = new Point(2,3);
var point2 = new Point(4,5);
var subtractedPoint = Point.distance(pont1,point2);
```

will produce this error

```
ReferenceError: pont1 is not defined
Stack trace:
userScript@user-script:localhost%3A8000/Issue%20with%20external%20script:370:5
scopeWrapper@user-script:localhost%3A8000/Issue%20with%20external%20script:479:9
@user-script:localhost%3A8000/Issue%20with%20external%20script:361:17
```

The script has nowhere near that many lines

It's even worse if there is an issue with a third-party script is involved

```javascript
// ==UserScript==
// @name        Issue with external script
// @require     https://cdn.rawgit.com/pnitsch/BitmapData.js/ddb2205fb44a7b02725288f30db34a0dd433d6eb/js/Point.js
// @version     1.0.0
// @grant       none
// ==/UserScript==

var point1 = new Point(2,3);
var point2 = new Point(4,5);
var subtractedPoint = Point.distance(point1,point2);
```

```
ReferenceError: p2 is not defined
Stack trace:
Point/Point.distance@user-script:localhost%3A8000/Issue%20with%20external%20script:410:7
userScript@user-script:localhost%3A8000/Issue%20with%20external%20script:370:23
scopeWrapper@user-script:localhost%3A8000/Issue%20with%20external%20script:479:9
@user-script:localhost%3A8000/Issue%20with%20external%20script:361:17
```

**Comment by NoneGiven** [comment] 2017-11-28 13:57
Dupe of #2584

**Comment by DoomTay** [comment] 2017-11-28 13:59
Oh. I was wondering if this was filed already. Evidently my search fu sucks.

**Comment by arantius** [comment] 2017-11-28 20:08
@Eselce 
> You have to reduce the given line number by ... overhead (some 350 lines) ... included @require sizes

How do you know this?  I admit it's only received some attention so far, but the _intent_ is that the first line of the main script is on the first line of the string passed to `tabs.executeScript()`.  Requires are after (the wrapper function around) the main script, not before.

But yes also, dupe.

**Closed by arantius** 2017-11-28 20:08 UTC

**Comment by Eselce** [comment] 2017-11-28 21:41
Hmm, I should examine this consciously, which I obviously did not before, I only migrated some scripts with many @require-d files, where I moved parts of the code. I am pretty sure, that errors in the main file had line numbers 6000+... (which means, main is after, not before much other code, but I should look into the sources for such a statement!)

**Comment by Eselce** [comment] 2017-11-28 21:43
BTW: Yes, dupe! I'm off...

**Comment by Eselce** [comment] 2017-11-29 23:49
Okay, I took a closer look at this (but it doesn't really fit into #2584):
```
// ==UserScript==
// @name        Internal script issue
// @require     https://cdn.rawgit.com/pnitsch/BitmapData.js/ddb2205fb44a7b02725288f30db34a0dd433d6eb/js/Point.js
// @version     1.0.0
// @grant       none
// ==/UserScript==

var point1 = new Point(2,3);
var point2 = new Point(4,5);
var subtractedPoint = Point.distance(pont1,point2);
```
```
ReferenceError: pont1 is not defined
Stack trace:
userScript@user-script:localhost%3A8000/Issue%20with%20external%20script:370:5
scopeWrapper@user-script:localhost%3A8000/Issue%20with%20external%20script:479:9
@user-script:localhost%3A8000/Issue%20with%20external%20script:361:17
```
The last stack dump line shows us the line offset plus one (360 + 1 = 361).
This is the supposed first line of the script (but it isn't for the error message).
Although `_evalContent` indeed starts with first line of the main script at
`line 1, col 57`, here this char will shift to `line 361, col 57`.

At `line 361, col 17` (see stack dump), you'll find this: `scopeWrapper(){ ...`
At `line 370, col 5` (see stack dump), the errornous assignment:
`subtractedPoint = Point.distance(pont1,point2)`

But when I look at the essential part, I also confused sth. (I assume 10 lines of code here):
```
[361]try { (function scopeWrapper(){ function userScript() { ${this._content}
[371]        /* Line break to catch comments on the final line of scripts. */ }
[372]        const unsafeWindow = window.wrappedJSObject;
[373]        ${this.calculateGmInfo()}
[...]        ${apiProviderSource(this)}
[...]        ${Object.values(this._requiresContent).join('\n\n')}
[479]        userScript();
[480]        })();
[481]        } catch (e) { console.error("Script error: ", e); }
[482]        //# sourceURL=user-script:${escape(this.id)}
```
Obviously, the main code starts at `361:57`, then `unsafeWindow`, then `GM`, `GM.info` and the other `API` functions, then the @require data, call of `userScript`, call of `scopeWrapper` (end), then `catch` and the download-URL comment...

My example had an error in the main script at line 6000+. But if I recall correctly, I got that bug report after moving much code into @require modules. Sadly the bug report was related to the single file version. That's why I confused it. Now I checked it again (on the split version):

`[2989] OS2.jugend (0.54+WE+): procSpielereinzelwerte(...) is undefined			OS2.jugend:3758:5
`
```
showAlert			user-script:http%3A//os.ongapo.com//OS2.jugend:3758:5
showException			user-script:http%3A//os.ongapo.com//OS2.jugend:3778:9
defaultCatch			user-script:http%3A//os.ongapo.com//OS2.jugend:3791:20
userScript/</<			user-script:http%3A//os.ongapo.com//OS2.jugend:2996:20
userScript/<			user-script:http%3A//os.ongapo.com//OS2.jugend:2974:6
userScript			user-script:http%3A//os.ongapo.com//OS2.jugend:2973:1
scopeWrapper			user-script:http%3A//os.ongapo.com//OS2.jugend:7152:9
<anonym>			user-script:http%3A//os.ongapo.com//OS2.jugend:361:17
```
This translates to:
```
line 2629 [2989] out of 2644 [3004]

line 2636:20 [2996] call defaultCatch()

line 2614:6 [2974] async
- line 2638 [2998]

line 2613:1 [2973] sync
```
This is at line 2639 [2999] out of 2644 [3004]:
```
userScript/</<			user-script:http%3A//os.ongapo.com//OS2.jugend:2999:13
```
The catch is two lines after the `userScript` call (in the first example `479 + 2 = 481`), here `7152 + 2 = 7154`
```
Script error:  main		OS2.jugend:7154:23
```
(BTW: Maybe it should better be `catch (e) { console.error("Script error:", e); }` to avoid this weird double space)

So the main script has a 360 line offset here (not zero), but the additional code and the @require code comes later...

And Tampermonkey isn't much better now (since FF 57):

`[6702] OS2.jugend (0.54+WE+): procSpielereinzelwerte(...) is undefined			ju.php:701:5`
```
showAlert					https://os.ongapo.com/ju.php:701:5
showException					https://os.ongapo.com/ju.php:721:9
defaultCatch					https://os.ongapo.com/ju.php:734:20
tms_eda15b4a_2b05_4e3f_a6ad_0f4ed6942fef/</<	https://os.ongapo.com/ju.php:6709:20
tms_eda15b4a_2b05_4e3f_a6ad_0f4ed6942fef/<	https://os.ongapo.com/ju.php:6687:6
tms_eda15b4a_2b05_4e3f_a6ad_0f4ed6942fef	https://os.ongapo.com/ju.php:6686:1
k</<						https://os.ongapo.com/ju.php:2:367
anonymous/<					https://os.ongapo.com/ju.php:4:1
anonymous/<					https://os.ongapo.com/ju.php:3:55
anonymous					https://os.ongapo.com/ju.php:3:2
k</<						https://os.ongapo.com/ju.php:2:367
E_c						https://os.ongapo.com/ju.php:3:190
ca						https://os.ongapo.com/ju.php:62:49
create						https://os.ongapo.com/ju.php:73:51
e						https://os.ongapo.com/ju.php:16:128
```
```
tms_eda15b4a_2b05_4e3f_a6ad_0f4ed6942fef/</<	https://os.ongapo.com/ju.php:6712:13
```
This is just a guess: If I add 1 line each between @requires (`gm4-polyfill` and others), I calculate 701 in `showAlert`, 721 in `showException` and 734 in `defaultCatch`. But the lines in the main file are sky high (around 6700), which is much worse!
```
line 2629 [6702] out of 2644 [6717]

line 2636:20 [6709] call defaultCatch()

line 2614:6 [6687] async
- line 2638 [6711]

line 2613:1 [6686] sync

line 2639 [6712] out of 2644 [6717]
```

**Comment by Sxderp** [comment] 2017-11-30 13:13
> So the main script has a 360 line offset here (not zero), but the additional code and the @require code comes later...
And Tampermonkey isn't much better now (since FF 57):

I think Tampermonkey puts the `@require` stuff before the main script, which causes the large offset?

Either way, it looks like it's a guaranteed offset of 360? We could probably catch the error adjust the line number and rethrow. Should work.

**Comment by arantius** [comment] 2017-11-30 14:08
> We could probably catch the error ...

Nope.  Only a small subset of them.

**Comment by Eselce** [comment] 2017-11-30 19:02
The "Script error:" catch wouldn't even catch async errors.
And what about caught exceptions? No way...
