### ISSUE TITLE
Add a "Create Script" button and/or "Manage" page

### ISSUE THREAD

**Issue by jeremyredhead** [greasemonkey/greasemonkey#2645] opened 2017-11-05 21:56 UTC
First, I just wanna say thank you and congratulations on converting to web ext, I know it wasn't easy.

Previously there was a button (or something) for the quick creation of a user script; now one would need to upload a script to gist or pastebin. This would be really nice to have.

There also used to be a full page for managing userscripts; it is possible from the popup, but inconvenient.

**Comment by arantius** [comment] 2017-11-05 23:09
I'll leave this open to track the feature, I do fully intend to add back missing features from 3.x eventually, this included.

Manage only from the popup is intentional.  Two interfaces is extra work for minimal benefit, and one interface this size will work equally well on mobile (Firefox for Android).

**Comment by Eselce** [comment] 2017-11-07 11:23
My workaround for a missing "New script"/"Create script" functionality:

Since I managed to install ONE script in a conventional way, I can now edit this "slot" for any adhoc (or pasted) script I want. Disadvantage: The number of installed scripts is constant. But it works for me until missing parts of the menu return to 4.x

**Comment by arantius** [comment] 2017-11-07 14:05
You should be able to edit the `@name`/`@namespace` to something else, then install the original script again.  (And if not, please report so in a distinct issue.)  But this is a temporary workaround, this proper feature will come back.

**Comment by Eselce** [comment] 2017-11-07 15:14
1) Confirmed, it works. (But the number stays constant: If I do that twice, I can paste/edit from scratch up to 2 scripts at a time)
2) Yes, I know! Will probably make my migration effort a lot easier...

**Comment by darkred** [comment] 2017-11-15 20:30
"Execution order" sorting is the feature I miss the most from the legacy full-tab "manage" dialog.
Currently (in GM 4.0), as it seems, the scripts are executed as they are listed in the popup, i.e. in alphabetical order. 
With this sorting no longer available, there's no quick way to resolve userscript conflicts anymore.

---

For reference, I quote from the (now removed) ['Script order' wiki page](http://web.archive.org/web/20160322010349/https://wiki.greasespot.net/Script_order) :

> ## _Script order_
> 
> _Scripts can be displayed in order by:_ 
> - _Status - Scripts are ordered by activation status: enabled or disabled, then name._
> - _Name - Scripts are ordered alphabetically by name regardless of status._
> - _**Execution order** - Scripts are ordered by execution index._
> 
> _This last order is important for user scripts that conflict with each other. By changing the order of the scripts the conflict can be resolved. You can change the order by right-clicking an user script and choose one of the actions: `Execute first`, `Execute sooner`, `Execute later` or `Execute last`._

**Comment by Sxderp** [comment] 2017-11-15 20:37
You should have created a new issue. But anyway. Wasn't aware of this. I didn't think GM guaranteed any such order. At least that's how I treated 3.x. 

Making the monkey menu draggable and have that order saved as execution order may be an idea.

**Comment by darkred** [comment] 2017-11-15 20:56
> You should have created a new issue.

Ok, I've deleted my comment and filed https://github.com/greasemonkey/greasemonkey/issues/2679

**Comment by arantius** [comment] 2017-11-23 17:31
Fixed by 93e8178e7ca6a6ed51eefe69b34def7d8db38759 and (some pending) improvements to that.

**Closed by arantius** 2017-11-23 17:31 UTC
