### ISSUE TITLE
Mysterious focus order when closing tabs opened by GM_openInTab

### ISSUE THREAD

**Issue by penguishPenguin** [greasemonkey/greasemonkey#2269] opened 2015-09-12 06:31 UTC
<pre><code>
var uris = [
'https://www.google.com/',                //<= Site D
'http://www.yahoo.com/',                  //<= Site C
'http://wiki.greasespot.net/Main_Page',   //<= Site B
'https://addons.mozilla.org/ja/firefox/'  //<= Site A
];

for (var uri of uris) {
    GM_openInTab(uri);
}
</code></pre>

When executing the script above on Site P, Greasemonkey opens Site A, B, C, D, and
tab order is {P}[A][B][C][D].
(Focused tab is bracketed with {}, and background tabs are bracketed with [])

{P}[A][B][C][D] <= switch tab from P to A
[P]{A}[B][C][D] <= close A
{P}[B][C][D] <= swith tab from P to B
[P]{B}[C][D] <= close B
[P]{C}[D] <= close C
{P}[D]

This behavior should be changed to Firefox default behavior.
{P}[1] <= open A and swithc forcus from P to A
[P]{A}[1] <= close A
{P}[1] <= open B, C and switch focus from P to B
[P]{B}[C][1] <= close B
[P]{C}[1] <= close C
[P]{1}

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:41.0) Gecko/20100101 Firefox/41.0
Greasemonkey 3.4

**Comment by janekptacijarabaci** [comment] 2015-09-12 08:58
If I understand correctly, the desired behavior...

I think this should be enough to resolve the problem:
https://github.com/greasemonkey/greasemonkey/blob/master/content/browser.js#L80
From:
`'ownerTab': scriptTab`
To:
`'ownerTab': null`

**Comment by arantius** [comment] 2015-09-12 15:23
Step one, I need a page with links to the example pages, so I'll add a comment that does that:

* Site D: https://www.google.com/
* Site C: http://www.yahoo.com/
* Site B: http://wiki.greasespot.net/Main_Page
* Site A: https://addons.mozilla.org/ja/firefox/

**Comment by arantius** [comment] 2015-09-12 15:27
I could have sworn that what you describe first was the default Firefox behavior, but I can't reproduce it so I'm obviously confused.

**Comment by penguishPenguin** [comment] 2015-09-13 03:54
I recorded videos.
Default Firefox Behavior when opening one tab and closing it
https://youtu.be/KcbF83_tJEs

Default Firefox Behavior when opening multiple tabs and closing them
https://youtu.be/G8_3Cqz_IA4

Behavior when opening multiple tabs with GM_openInTab and closing them
https://youtu.be/WpmV5Rs4qww

**Comment by janekptacijarabaci** [comment] 2015-09-13 05:13
So I understood correctly.

**Comment by arantius** [comment] 2015-09-17 16:24
I've reproduced my expected behavior.  It might depend on preferences, I'm not sure.

1. Open a page with links, e.g. https://github.com/greasemonkey/greasemonkey/issues
2. Open two of them in background tabs.
3. Open one of them in a foreground tab.

You've now got four tabs; the original, two background tabs never focused, one new tab opened in the foreground.  Focus any of the three just opened (or stay on the already focused one) and close it: you end up on the original tab.  But that act of closing a tab breaks the relationship between the opener and the children, so now focusing goes to the left.

**Comment by arantius** [comment] 2015-11-20 20:19
Tab behavior is a varied and complex thing, so I've built an experiment.  First a testbed: [tab-order.html](https://gist.github.com/arantius/e5b0bbff7ba341f06b6a).

Firefox 42.0, brand new completely blank profile, no extensions, all default preferences.  Notation below: Letter T is the test page, letters A B C D are the sub-pages opened from it.  Asterisks surround the tab with focus.

1. Click the "Plain" links and, no surprise, you navigate with no new tabs.  Not applicable.
2. Ctrl-click or middle-click or right click>new tab the "plain" links.
  1. You now have *T*ABCD.
  2. Focus A, close it, now T*B*CD.
  3. Close B, T*C*D.
  4. Close C, T*D*.
  5. Close D, *T*.
3. Left click on the "_blank" links.
  1. Each is focused immediately.  So re-focus T each time to continue.
  2. You now T*D*CBA.
  3. Close D, now *T*CBA.
  4. Focus C, close it, now T*B*A.
  5. Close B, now T*A*.
  6. Close A, now *T*.
4. Left click the "window.open()" links.
  1. Behavior is identical to case three.
5. Click the "Open x4" button.  This is closest to the originally reported case, as a script opens all four at once.
  1. Get TABC*D*.
  2. Close D, now TAB*C*.
  3. Close C, now TA*B*.
  4. Close B, now T*A*.
  5. Close A, now *T*.
6. For clarity, install GM (3.6) and run a script* like that in the original report.
  1. My script opens A B C D in that order, just like all above cases.
  2. Tabs are *T*DCBA.
  3. Focus D, close it, now *T*CBA.
  4. Focus C, close it, now T*B*A.
  5. Close B, now *T*A.
  6. Focus A, close it, now *T*.
7. Edit the script to pass `false` for `open_in_background`.
  1. Get T*D*CBA.  (They should be in ABCD order, like case two?)
  2. Close D, now T*C*BA.
  3. Close C, now T*B*A.
  4. Close B, now T*A*.
  5. Close A, now *T*.

There's several important things to note.  With just stock Firefox, no extensions, no preferences changed, there is no "default behavior".  Cases two through five differ in where the focus goes at each step.  Sometimes focus stays "in place" (two), sometimes it shifts back to the parent (three), sometimes to an adjacent tab (5).  The key details are how the tabs were opened, and when/whether focus is manually changed.  

So which of case two through five should we aim to emulate for case six?  For case seven?

----

*The exact script I ran for case 6:

```javascript
// ==UserScript==
// @name     Open Test
// @grant    GM_openInTab
// @include  *tab-order.html
// ==/UserScript==

GM_openInTab('?A');
GM_openInTab('?B');
GM_openInTab('?C');
GM_openInTab('?D');
```

**Comment by arantius** [comment] 2015-11-20 20:21
Crap, asterisks->italics.  Still works overall, just pay attention for which letter is in italics.

**Comment by arantius** [comment] 2015-11-20 21:32
[openLinkIn](http://mxr.mozilla.org/mozilla-central/source/browser/base/content/utilityOverlay.js#198) gives us sweet, sweet default behavior.  But doesn't return a handle to the new tab.  Other features (force fore/back-ground, force non-/related position) require that handle...

**Comment by janekptacijarabaci** [comment] 2015-11-21 18:26
What about this "fix"?
https://github.com/janekptacijarabaci/greasemonkey/tree/_testBranch_GM_openInTab_focus

**Comment by penguishPenguin** [comment] 2015-11-30 14:58
I think the default behavior is below.

1. behavior of opening tab
Firefox remembers the tab relationship and
opens new tab at the right side of the last opened tab until
tab focus is changed.
(If focused tab has no child tab, open new tab at the right side of focused tab)
Once tab focus is changed, Firefox forgets the tab relationship and
opens new tab at the right side of focused tab.

2. behavior of closing focused tab
Basically, move to the right side of closed tab.
Exceptionally, move to parent tab if closed tab was opened in foreground and
tab focus hasn't beed changed.
Once tab focus is changed, Firefox forgets this tab relationship and
moves focus to the right side of closed tab.

If possible, I think emulating this behavior is the best.
If impossible or too complicated, I think the second best behavior is below.

1. behavior of opening tab
Greasemonkey opens a tab at the right side of focused tab.

2. behavior of closing focused tab
Greasemonkey moves focus to the right side of closed tab.

**Comment by arantius** [comment] 2016-03-04 20:19
https://bugzilla.mozilla.org/show_bug.cgi?id=1253705

**Comment by mzso** [comment] 2016-03-07 11:26
[**@arantius**](https://github.com/arantius) commented on [2016. márc. 4. 21:19 CET](https://github.com/greasemonkey/greasemonkey/issues/2269#issuecomment-192448939 "2016-03-04T20:19:30Z - Replied by Github Comment Enhancer"):
> [https://bugzilla.mozilla.org/show_bug.cgi?id=1253705](https://bugzilla.mozilla.org/show_bug.cgi?id=1253705)

Is this relevant to #2365 too? 
The TMP dev proposed some changes there to solve the issue between the two addons.

**Comment by arantius** [comment] 2016-08-02 13:47
So, my attempt to push this fix upstream was denied.  I don't have an idea I like on how to improve this behavior.

**Comment by janekptacijarabaci** [comment] 2016-08-02 14:40
AFAIK: This is a dirty solution better than nothing:
https://github.com/janekptacijarabaci/greasemonkey/commit/a284795d5ce50d971a26a6e5f4133dd76065b530

**Closed** 2017-07-25 13:58 UTC
