### ISSUE TITLE
Direct Image URLS No Longer Showing Images for Many Sites

### ISSUE THREAD

**Issue by Zetawilk** [greasemonkey/greasemonkey#2554] opened 2017-08-30 18:40 UTC
Many websites with links directly to image URLs are no longer displaying those images at the image URL when Greasemonkey is enabled.

**Comment by eight04** [comment] 2017-08-31 02:00
Probably duplicate of #2524.

**Comment by ssixty** [comment] 2017-08-31 18:16
Could we get #2524 re-opened please?

**Closed** 2017-08-31 19:27 UTC

**Comment by janekptacijarabaci** [comment] 2017-09-07 19:17
See also https://github.com/gorhill/uBlock/issues/2930#issuecomment-325972269
