### ISSUE TITLE
[Request] Gm_closeTab

### ISSUE THREAD

**Issue by erosman** [greasemonkey/greasemonkey#2125] opened 2015-03-23 12:09 UTC
There are times that closing a tab is required. I am not keen on enabling `dom.allow_scripts_to_close_windows`

Currently, I overcome the issue with a lot of additional code but a built-in function would be greatly beneficial.

````JavaScript
function GM_closeTab() {
  // get the current tab first then ...
  gBrowser.removeCurrentTab();
}
````

**Comment by janekptacijarabaci** [comment] 2015-03-23 12:15
Duplicate of issue #1685.

**Comment by erosman** [comment] 2015-03-23 12:29
#1685. Wow .... 7 Jan 2013
I guess the feature is not coming...

**Closed** 2015-03-23 14:05 UTC
