### ISSUE TITLE
Add a way for scripts to define settings

### ISSUE THREAD

**Issue by ExE-Boss** [greasemonkey/greasemonkey#2517] opened 2017-06-20 19:32 UTC
This would make it easier to change the settings of scripts for people who don’t understand JavaScript and to change the settings of minified scripts.

## Example implementation:
After the `==UserScript==`...`==/UserScript==` block there would be an optional `==UserScriptSettings==`...`==/UserScriptSettings==` block.

### `==UserScriptSettings==`...`==/UserScriptSettings==` block
The block would contain the following parameters:

#### [`@param`](http://usejsdoc.org/tags-param.html)
This parameter defines a script setting.

##### Contains the following arguments:
1. The JS type (enclosed in curvy brackets `{...}`) – Defines the value type
    - If formatted as `{...=...}` then the content after `=` will be the default value, parsed as a JSON type (number/string/boolean/array/object).
2. The setting ID (optionally enclosed in square brackets `[...]`, brackets required if the ID contains symbols that are not valid for standard JavaScript identifiers)
3. The setting name and description

#### `GM_getConfig(setting)`
Gets the specified script setting.

##### Parameters:
- `{String} setting` The setting ID

##### Returns:
The value of the setting as defined by the user.

**Comment by arantius** [comment] 2017-06-20 20:35
As has always been the policy, GM doesn't add features that are already possible in "user space".  See e.g. https://github.com/sizzlemctwizzle/GM_config

(Also, dupe of #1860 )

**Closed by arantius** 2017-06-20 20:35 UTC

**Comment by eight04** [comment] 2017-06-20 22:24
👍

I think this feature is nice to script developers and we can avoid requiring `GM_config` for each different script. Is there any chance to introduce a config API on WebExt version? It even doesn't need synced get/setValue.

> GM doesn't add features that are already possible in "user space".

What about `GM_addStyle`?
