### ISSUE TITLE
cannot access javascript-variable of original page

### ISSUE THREAD

**Issue by McBen** [greasemonkey/greasemonkey#2653] opened 2017-11-09 11:24 UTC
Greasemonkey 4.1beta2
Firefox 58.0b1 - Linux/Kubuntu

a script example for:
http://www.greasespot.net/

(picked a random variable to display in a alert-dialog)

```
// ==UserScript==
// @name hello
// @namespace world
// @include http://www.greasespot.net/
// @grant          none
// ==/UserScript==

alert(window['__wavt']);

```

should display a dialog with a 'guid' but only show 'undefined'

**Comment by Sxderp** [comment] 2017-11-09 13:47
This is not a Grease Monkey issue. Although it could be documented.
Content scripts (which is the context in which Grease Monkey runs user scripts) do not have direct access to webpage Java content. They get a clean window object. In order to access it you need the 'unwrapped' window.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Accessing_page_script_objects_from_content_scripts

```javascript
var unsafeWindow = window.wrappedJSObject;
alert(unsafeWindow['__wavt']);
```

If you need to import an object into the content script context then you have to use cloneInto.

```javascript
var unsafeWindow = window.wrappedJSObject;
var object_to_be_cloned = {'key': 'value'};
var unsafeWindow.cloned_object = cloneInto(object_to_be_cloned, window);
// unsafeWindow.cloned_object is now accessible by the page. The page would access it with the
// standard window.cloned_object
```

**Comment by arantius** [comment] 2017-11-09 14:13
It is.  `@grant none` doesn't work like it used to.  In 3.x the original script would have worked.

Practically though, this is a dupe of #2549.

**Closed by arantius** 2017-11-09 14:13 UTC

**Comment by McBen** [comment] 2017-11-09 19:46
uhh...thats bad.
so it's no longer compatible with chrome/tampermonkey?

**Comment by tobbexiv** [comment] 2017-11-09 21:53
Don't use window, but you own variable and assign either `window` or `window.wrappedJSObject` to this variable, depending on the scope. Then it should still run in both situations. But this is nothing from GM, but from Firefox.
