### ISSUE TITLE
Editing user script causes @require to fail loading

### ISSUE THREAD

**Issue by vzjrz** [greasemonkey/greasemonkey#2683] opened 2017-11-16 04:57 UTC
Firefox 57 GM 4.1beta3
I've upgraded from the older greasemonkey and now am in the process of fixing my scripts but I noticed that if you edit something and then save greasemonkey sometimes doesn't get the @require scripts.
```
// ==UserScript==
// @name          Test
// @include       *://github.com/*
// @require       https://code.jquery.com/jquery-3.1.1.min.js
// @require       https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
// @grant         GM.addStyle
// @grant         GM_addStyle
// @run-at        document-idle
// @noframes
// ==/UserScript==

(function () {
	'use strict';

	console.log($);
	console.log(GM_addStyle);
})();
```

```
 Script error:  
ReferenceError: $ is not defined
```
In order to get it to work I need to:

1. Do my edits
2. Save
3. Add a `?` character to the end of each @require url
4. Save
5. Remove the extra characters from the @require urls
6. Save

That seems to fix it.

**Comment by StigNygaard** [comment] 2017-11-16 06:55
I haven't investigated so much as vzjz, but I have had similar problems.

**Comment by Eselce** [comment] 2017-11-16 08:44
I've had several issues: No update of depending script resources after editing.

**Comment by Sxderp** [comment] 2017-11-16 13:31
I've actually run into this once before too. I just figured it was something in my environment due to screwy testing.

Can someone confirm if (from following the instructions in first post)

7. Make some changes
8. It happens again?

**Comment by Sxderp** [comment] 2017-11-16 18:56
#2689 may help with this.

**Comment by StigNygaard** [comment] 2017-11-17 06:21
Hi @Sxderp , how "deep" does fix for #2689 go? The reason I ask is, that as far as I remember when seeing the issue, it was not only an UI problem. The userscript also stopped working because it couldn't find the require'd sub-script.
Sorry, haven't had time to investigate more. So it's only as I remember it...

**Comment by Pantalaim0n** [comment] 2017-11-17 18:35
@Sxderp I can confirm the issue exists when making changes to the script, the @require does not work.

**Comment by Sxderp** [comment] 2017-11-17 20:16
Alright, I was able to reproduce this. Not sure if the execution workflow what I forced is similar to others.

1. Make some basic script (that works).
2. **Add** a @requires
3. Force an indexedDB error[1]. Do this by having two scripts with the same name. That is, rename the script you're working on to something already existing.
4. Save
5. Fix the error.
6. Save
7. Continue editing without touching the @requires
8. Save
9. Run the script and the @requires is not there. Further editing of the script does not solve the problem.

The problem caused, with my workflow is due to the caching. Short on time, so do not have a full explanation at the moment.

[1] These errors are silent in the editor UI. Shows up in the browser console though.

**Comment by arantius** [comment] 2017-11-17 21:27
The above change (#2689) is in version 4.1beta4.  Testing to confirm the fix is appreciated!

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta?page=1#version-4.1beta4

**Comment by Sxderp** [comment] 2017-11-17 21:45
> The above change (#2689) is in version 4.1beta4. Testing to confirm the fix is appreciated!

I don't believe it does fix it. At the time I made the comment regarding it I thought it _might_ help since the tabs are iterated through in order to send the resources to the backend. Turns out that doesn't quite resolve this issue.

The steps I listed above still produce the error. I'll provide more details soon-ish.

**Comment by MegaScience** [comment] 2017-11-17 22:18
Hmm. I tried the beta and rearranging resources via editing wasn't making the polyfill stop loading, which is nice. Still, I'd like confirmation that there aren't still edge cases.

**Comment by Sxderp** [comment] 2017-11-17 23:31
Alright, I've figured out what's happening.

Setup: Add this script.
```javascript
// ==UserScript==
// @name        test
// @include     https://google.com
// @run-at      document-idle
// ==/UserScript==
console.log('We do not do anything.');
```

---

Now create a new script and paste the following **1**.
```javascript
// ==UserScript==
// @name        testI
// @namespace   ncgamers.org
// @require     https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.js
// @run-at      document-idle
// ==/UserScript==
(function() {
  var jQ = typeof jQuery !== 'undefined' ? jQuery : null;
  console.log('Should be null, initial script', jQ);
})();
```
Check everything is working. There should be no problems.
Then paste the following **2**. It changes the name to conflict, adds a requires, and adjusts the message a bit.
```javascript
// ==UserScript==
// @name        test
// @namespace   ncgamers.org
// @require     https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.js
// @run-at      document-idle
// ==/UserScript==
(function() {
  var jQ = typeof jQuery !== 'undefined' ? jQuery : null;
  console.log('Should be defined, bad name + require', jQ);
})();
```
Now, if you check the logs you'll see an error saying that the transaction failed. We'll get back to this. You'll also notice that that no tab is created, which, following the previous updates, there should have been one.
However, if you check the script. Everything is working. The jQuery object is valid. In order to fix (well, break) that, just make another change. Any change really **3**.
```javascript
// ==UserScript==
// @name        test
// @namespace   ncgamers.org
// @require     https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.js
// @run-at      document-idle
// ==/UserScript==
(function() {
  var jQ = typeof jQuery !== 'undefined' ? jQuery : null;
  console.log('Should be null, bad name + require + content modified', jQ);
})();
```
Great, now we have a broken requires. Why?

The majority of the issue comes from the bad transaction I discussed earlier. As well as partially from the what I presume is a **feature**. You can modify a @requires content and have Greasemonkey track those changes.

Initially in **1** we create a script. Nothing special. In **2** is where the magic happens. Greasemonkey does not allow two scripts to have the same [namespace + name](https://github.com/greasemonkey/greasemonkey/blob/64f1ae1945c54ad343a2aad896b72a71f86fd07a/src/bg/user-script-registry.js#L36). What happens is that we end up going down the [error codepath](https://github.com/greasemonkey/greasemonkey/blob/64f1ae1945c54ad343a2aad896b72a71f86fd07a/src/bg/user-script-registry.js#L235-L238) and never send the 'UserScriptChanged' message.

At first glance it may seem like this doesn't matter, the script wasn't saved so we don't need to send the message, right? Well, no. The object that is loaded into memory changed. Changed two very important properties `requireUrls` and `requireContent`. Since these properties changed it seems like everything is working. But it's really not. Since 'UserScriptChanged' is never sent, the tabs are once again desynced and performing a third save **3** causes everything to break.


How? Well, due to the **feature** described above (like paragraph 1) the `_requireContent` property is set based on what is [returned from the editor](https://github.com/greasemonkey/greasemonkey/blob/64f1ae1945c54ad343a2aad896b72a71f86fd07a/src/user-script-obj.js#L299) from the editor. If the editor has nothing to send (re: no tabs), then nothing is set. Under normal circumstances this wouldn't be a problem, as GM _should_ fetch the content. But in this circumstance the `newDetails` and `oldDetails` will have the same [requireUrls](https://github.com/greasemonkey/greasemonkey/blob/64f1ae1945c54ad343a2aad896b72a71f86fd07a/src/user-script-obj.js#L396-L401) and nothing is fetched.

---

That was probably a lot longer than need be.

Since the scope of this is pretty encompassing there's probably a lot of ways to go about fixing it. One way that I like is to modify the [onerror part of saveUserScript](https://github.com/greasemonkey/greasemonkey/blob/64f1ae1945c54ad343a2aad896b72a71f86fd07a/src/bg/user-script-registry.js#L235-L238). I'd add a message that sends  the 'UserScriptChanged' with the current in memory script (yes, even though it errored) and then send a [notification](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications) saying the save failed, if possible adding a reason, and stating it won't persist on reload.

**Comment by arantius** [comment] 2017-11-19 17:02
> ...add a message that sends the 'UserScriptChanged' with the current in memory script (yes, even though it errored) and then send a notification saying the save failed, if possible adding a reason, and stating it won't persist on reload.

This is pretty close to 3.x behavior, and is definitely an improvement.

**Comment by Sxderp** [comment] 2017-11-21 17:17
> This is pretty close to 3.x behavior, and is definitely an improvement.

So, my comments weren't 100% clear and I've hit a 'which should be sent back' wall, as well as 'what should stay in memory and be executed (even if it doesn't persist on reload)'?

Options are

1. Send back the current state of the editor. So if someone adds a new `@require` and the save fails then no new tabs are created. AND revert[1] any changes made to the current in-memory script (the one that would be executed).
2. Send back what would have been new state / newly saved script. So if someone adds a new `@require` and the save fails then a new tab is created. AND revert[1] any changes made to the current in memory script (the one that would be executed).
3. Send back what would have been new state / newly saved script. BUT don't revert[1] any changes made to the current in memory script.

[1] At the moment when [updating from editor](https://github.com/greasemonkey/greasemonkey/blob/64f1ae1945c54ad343a2aad896b72a71f86fd07a/src/bg/user-script-registry.js#L122-L132) the current in memory script is modified in place. In order to allow for reverting I'd make a clone, make changes on the clone, and then if the save succeeded assign the cloned to the `userScripts` object in the registry.

**Comment by Sxderp** [comment] 2017-11-21 17:22
I like option 2.

**Comment by arantius** [comment] 2017-11-21 20:50
Agree about edit the clone.  If the save didn't work, nothing in my editor should change.  I should be able to fix it and save what I tried to originally (modulus fixes) again.

**Comment by arantius** [comment] 2017-12-04 20:46
Ok at head as of now, use monkey menu to make new script, add a `console.log()`, load pages and see the message.

Edit the script to add a valid `@require`, load more pages, still see the console message.  Make a few more edits, continue to see the script running and working as expected.

Closing this.  @Sxderp you're talking about valid improvements above, please make an issue to track those other enhancements, outside of this bug-fix issue which seems to be complete.

**Comment by Sxderp** [comment] 2017-12-06 14:20
This isn't actually fixed. Basic editing of a script wasn't what caused the issue, the issue was caused by something (anything, but easily reproducible with duplicate name + namespace) causing a transaction error. If you follow my steps [here](https://github.com/greasemonkey/greasemonkey/issues/2683#issuecomment-345393724)[1] you should still see the error.

I think the problem was just more noticeable before because we had to use some remote script to even get userscripts into the GM database, there was no new script button. This, I imagine, lead to some, accidental, name + namespace duplication (or other transactional error) causing this bug.

[1] When my steps were initially posted there was an error with them which made it so they didn't cause the problem. This was fixed a few days ago.

**Comment by rogerlos** [comment] 2017-12-07 10:57
If it helps, I've found simply having the editor open causes this to happen, without a need to even create a new script with a conflicting namespace, etc. The act of having the editor open itself and refreshing a page where that script loads in another tab will trigger this error if the script has been saved during the editing session.

**Comment by Sxderp** [comment] 2017-12-07 13:41
> If it helps, I've found simply having the editor open causes this to happen, without a need to even create a new script with a conflicting namespace, etc. The act of having the editor open itself and refreshing a page where that script loads in another tab will trigger this error if the script has been saved during the editing session.

I cannot reproduce by 'simply' having the editor open. Made changes, modified requires etc.

If your script is already broken (that is the require isn't loaded) then the only way to fix that is to adjust the require line (adding a param or something) and then change it back. Doing any other changes / saving won't fix it.

**Comment by fletchowns** [comment] 2017-12-07 19:42
Starting in Firefox 57 I get an error when installing my userscript which uses an @require statement to load jquery:
```
Download error at https://code.jquery.com/jquery-2.1.1.min.js: 0 (Unknown)
```

Tried with the latest 4.0beta6 and still hitting it. Is my issue unrelated to what is being investigated in this ticket?

**Comment by arantius** [comment] 2017-12-07 19:59
Yes it is unrelated.

**Comment by SD-DAken** [comment] 2017-12-07 22:45
I can reproduce the problem with these steps:
1) Start with this userscript:
```
// ==UserScript==
// @name     Unnamed Script 2017-12-07 21:52:08
// @version  1
// @include  http://example.com/
// @require  https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js
// @grant    none
// ==/UserScript==

alert(typeof JSZip);
```
2) Go to http://example.com. An alert box with "function" opens (correct).
3) Switch back to editing the userscript and change the `//@grant none` to `//@grant GM.xmlHttpRequest`. Save the changes. The userscript should now be:
```
// ==UserScript==
// @name     Unnamed Script 2017-12-07 21:52:08
// @version  1
// @include  http://example.com/
// @require  https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js
// @grant    GM.xmlHttpRequest
// ==/UserScript==

alert(typeof JSZip);
```
4) Switch back to the example.com tab and reload it, you'll now get an alert box with "undefined" (broken).

**Comment by Sxderp** [comment] 2017-12-13 14:54
@SD-Daken, can't reproduce with FF52 ESR on current master. What version of Firefox and GM are you using?

**Comment by SD-DAken** [comment] 2017-12-13 16:11
I used Firefox 57.0.1 / Greasemonkey 4.0

I have not yet retested with Greasemonkey 4.1

**Comment by SD-DAken** [comment] 2017-12-13 16:57
> I have not yet retested with Greasemonkey 4.1

Not reproducible with Greasemonkey 4.1.

**Comment by arantius** [comment] 2018-01-05 15:49
Note to future self, remaining issue is described in [this comment](https://github.com/greasemonkey/greasemonkey/issues/2683#issuecomment-345393724) above.

**Closed** 2018-02-05 20:11 UTC
