### ISSUE TITLE
Firefox 57 GM4.0 userscripts won't install

### ISSUE THREAD

**Issue by darkred3** [greasemonkey/greasemonkey#2677] opened 2017-11-15 19:41 UTC
4chanX installs like a charm but scripts like webcomic reader or x-links won't prompt an install, just opens the raw user.js

https://github.com/anka-213/webcomic_reader/raw/master/webcomic_reader.user.js
https://raw.githubusercontent.com/dnsev-h/x-links/stable/builds/x-links.user.js

**Comment by Sxderp** [comment] 2017-11-15 20:14
They pop for me. Errors in console? Crtl+shift+j and Ctrl+shift+k

**Comment by tobbexiv** [comment] 2017-11-15 20:52
They do not ask for installation for me, too.

No issue in the web console, only this error in the browser console:
Error: Could not establish connection. Receiving end does not exist.  undefined

**Comment by xor10** [comment] 2017-11-15 20:53
Duplicate of #2631

**Comment by arantius** [comment] 2017-11-15 21:24
Probably reason to prioritize a fix for that more highly.

**Closed by arantius** 2017-11-15 21:24 UTC
Labels: duplicate
