### ISSUE TITLE
Javascript errors don't show up in the web console.

### ISSUE THREAD

**Issue by PotcFdk** [greasemonkey/greasemonkey#2219] opened 2015-07-15 19:12 UTC
I noticed, that none of my browser setups currently show errors in the web console, that were caused by Greasemonkey scripts:

![missing errors (screenshot)](https://threekelv.in/~potcfdk/tmp/2015-07-15_21-01-22.png)

Test machine:
Windows 7 x64
Firefox version 39.0
Greasemonkey is the only active addon
DevTest1 is the only active userscript

**Comment by arantius** [comment] 2015-07-15 19:17
Dupe of #2117 as far as I can tell.

**Closed by arantius** 2015-07-15 19:17 UTC
