### ISSUE TITLE
Sync: Could not get engine

### ISSUE THREAD

**Issue by yurikhan** [greasemonkey/greasemonkey#2351] opened 2016-01-11 12:52 UTC
I am on Firefox 43.0.4, Greasemonkey 3.6. My local Greasemonkey scripts do not sync, although the “Enable Firefox Sync for User Scripts” checkbox in Greasemonkey preferences is checked.

When I set the `services.sync.log.appender.file.logOnSuccess` preference to `true` and perform sync, I get [this log][1]. This line looks suspicious:

```
1452516132631	Sync.EngineManager	DEBUG	Could not get engine: greasemonkey
```

Is that normal? What else should I check?

[1]: https://gist.github.com/yurikhan/0360d2e4bdbc454c6092

**Comment by janekptacijarabaci** [comment] 2016-01-11 15:36
See also https://github.com/greasemonkey/greasemonkey/issues/2335

**Comment by yurikhan** [comment] 2016-01-11 16:03
Saw that ticket, but logs there show much more Greasemonkey-related sync activity that I observe here.

**Comment by janekptacijarabaci** [comment] 2016-01-12 16:03
"See also ..." = There is another thread discussing similar issues :-)

**Comment by arantius** [comment] 2016-03-04 17:22
This issue should be fixed in version 3.8beta2.  If you're experiencing this problem, please: 1) confirm you're still experiencing it, 2) describe how you confirmed that, 3) install 3.8beta2, 4) check whether it's fixed, 5) describe whether it's fixed or not, and how you know that.

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/?page=1#version-3.8beta2

**Comment by yurikhan** [comment] 2016-03-04 17:58
1: I experience the problem.

2: I know because I have Firefox with Greasemonkey at home and at work. They sync bookmarks and Stylish userstyles, but not Greasemonkey scripts. The option in Greasemonkey preferences is set on both instances.

3: I have installed 3.8beta2 on both systems.

4: I still have *a* problem, but not necessary this same problem.

5: I restarted both instances and clicked Tools | Sync Now first on the home instance, then on the work instance. The local scripts I have at home did not sync over to work. The “Could not get engine” message is no longer in the log. Here are Greasemonkey-related log entries:

```
1457113700587	Sync.Tracker.Greasemonkey	DEBUG	Saving changed IDs to greasemonkey
…
1457114041855	Sync.Service	INFO	Testing info/collections: {"clients":1457113541.69,"crypto":1426592609,"stylishsync":1456657023.87,"meta":1428853520.49,"bookmarks":1456812431.83,"prefs":1456811517.97,"greasemonkey":1444222466.42}
…
1457114041861	Sync.Engine.Greasemonkey	INFO	0 outgoing items pre-reconciliation
1457114041862	Sync.Engine.Greasemonkey	INFO	Records: 0 applied, 0 successfully, 0 failed to apply, 0 newly failed to apply, 0 reconciled.
```

The full log is [here].

[here]: https://gist.github.com/yurikhan/592beb9ab11764731ebc

**Comment by janekptacijarabaci** [comment] 2016-03-07 09:13
@yurikhan

If they are local scripts: see https://github.com/greasemonkey/greasemonkey/blob/3.7/modules/sync.js#L179

**Comment by yurikhan** [comment] 2016-03-07 11:50
So, Sync in Greasemonkey just synchronizes the URLs of scripts installed from remote locations, not the scripts themselves? Why is that useful?

**Comment by arantius** [comment] 2016-04-18 16:04
> Why is that useful?

Because normal users get the same scripts installed on all machines.  Sounds like this is all working as intended.

**Closed by arantius** 2016-04-18 16:04 UTC

**Comment by yurikhan** [comment] 2016-04-18 16:06
So, if I want to write scripts on one machine and have them replicated to my other machines, what do I do? File another issue?

**Comment by arantius** [comment] 2016-04-18 19:20
There's a very strict limit to the number of bytes in Sync data (on Mozilla's servers, at least), so such a feature would not "work", general case.  You need to solve this yourself.
