### ISSUE TITLE
At document-start time, some (unpredictable) parts of the document are already present

### ISSUE THREAD

**Issue by kekkc** [greasemonkey/greasemonkey#1849] opened 2013-12-29 22:51 UTC
Hello all,

the following event for the add of the title tag is not fired on http://www.example.com/ (alert is not shown):

```
// ==UserScript==
// @name        rtzgrgd
// @namespace   fhdf
// @description fdhdrfhdrfg
// @version     1
// @include     http*
// @grant       none
// @run-at document-start
// ==/UserScript==

MutationObserver = window.MutationObserver;
var observer = new MutationObserver(function(mutations) {
  mutations.forEach(function(mutation) {

    var addedNodes = mutation.addedNodes;
    for (var i = 0; i < addedNodes.length; i++) {
        if (addedNodes[i].nodeName == 'TITLE') {alert("Yes, script is active! Hurray!");}
    }

  });
});

// pass in the target node, as well as the observer options
observer.observe(document, {childList: true, subtree: true, attributes: true});
```

However, if the source of http://www.example.com/ is saved locally and the script is added there (as <script..</script> without using GM), everything works, event fires, alert is shown:
- see the attached example.com.htm

Besides, the user.js script is even working in Chrome (added in settings>extensions). So I guess it's not a problem in FF or the code. Somehow GM seems to swallow up all events, without giving them back. I have this problem with several userscripts (on some sites they're simply not active). This drives me crazy, if anyone has an idea about the problem or workaround please help ;)

Testcase to see that it's generally working without GM:
https://groups.google.com/group/greasemonkey-users/attach/bf08c3c428beeaa6/example.com.htm?part=4&view=1

Userscript for GM:
https://groups.google.com/group/greasemonkey-users/attach/bf08c3c428beeaa6/rtzgrgd.user.js?part=5&view=1

Greetz

**Comment by meitar** [comment] 2015-03-10 03:19
I'm not sure if I'm experiencing the same problem, or a similar one, but I think I just ran into this issue, too. **This is a showstopper for me.**

I'm developing a user script that uses a Mutation Observer to watch for subtree changes, and while my script works in Firefox if I just copy and paste the thing into the JS console, the entire script execution ends the moment I call `.observe()` on my `MutationObserver` object. Code:

```javascript
/**
 * This is a Greasemonkey script and must be run using a Greasemonkey-compatible browser.
 *
 * @author maymay <meitar@joindiaspora.com>
 */
// ==UserScript==
// @name           Test Mutation Observer Errors
// @version        0.1
// @namespace      net.maymay.tests
// @updateURL      https://github.com/meitar/TK-SOME-NAME-HERE/dermalinker.user.js
// @description    Test case to ensure I'm not going crazy.
// @include        https://*/*
// @grant          GM_xmlhttpRequest
// @grant          GM_addStyle
// @grant          GM_log
// ==/UserScript==

    var MutationObserver = unsafeWindow.MutationObserver || unsafeWindow.WebKitMutationObserver;
    var observer = new MutationObserver(function (mutations) {
        mutations.forEach(function (mutation) {
            console.log(mutation);
        });
    });
    var el = document.getElementById('SOME-ID');
    var config = {
        'childList': true,
        'subtree': true
    };
    console.log(observer); // confirm observer is present
    observer.observe(el, config); // this line breaks the whole script; if I comment this line out, everything else works without a problem, and I see the "got here" message in the console output
    console.log('got here')
```

Can someone who's more familiar with this issue let me know if this is related or if I should create a new issue for this?

Thanks.

**Comment by ngyikp** [comment] 2015-03-10 10:52
@meitar
I use MutationObservers on my user scripts just fine.

Try wrapping your problematic statement with a try/catch, you'll probably get a TypeError:

```javascript
console.log(observer); // confirm observer is present
try {
    observer.observe(el, config);
} catch (e) {
    console.log(e);
}
console.log('got here')
```

Most likely the reason why it works on the JS console and not inside a user script is probably because the user script is running way before the `el` even entered the DOM, you should wrap it like:

```javascript
var loop = function() {
    var el = document.getElementById('SOME-ID');
    if (el) {
        observer.observe(el, config);
    } else {
        // not there yet, retry again after a short while
        setTimeout(loop, 100);
    }
};
loop();
```

P.S. you don't need to use unsafeWindow to access MutationObserver.

**Comment by meitar** [comment] 2015-03-10 18:04
Thanks for the quick reply, @ngyikp, but unfortunately that's not the issue. Invoking `console.log` immediately before `observer.observe`  shows the target node (`el`) is indeed present. The issue remains.

**Comment by meitar** [comment] 2015-03-10 19:03
@ngyikp, your suggestion of wrapping the problematic line in try/catch blocks does help me see what some more errors are, thanks. :) Unfortunately, I still don't know why they are happening on mutation observers, which I was expecting would work without issue (as they do for you?). Specifically, the error that calling the `.observe()` method raises is this one:

    Error: Permission denied to access property 'attributeFilter'

I'm aware of [the changes in Firefox 30 relating to `unsafeWindow` and content scripts](https://blog.mozilla.org/addons/2014/04/10/changes-to-unsafewindow-for-the-add-on-sdk/) but, again, I was under the impression that these changes *do not* affect Mutation Observers, so I'm stumped why this error is being thrown in this extremely simple test case?

**Comment by meitar** [comment] 2015-03-13 08:44
So, for anyone who wants to replicate my issue, here is [the complete userscript working without any problems in Tampermonkey under Google Chrome](https://github.com/meitar/cross-pod-links/blob/master/cross-pod-links.user.js). This exact same userscript works in Tampermonkey/Chrome but fails to run at all in Greasemonkey/Firefox, as [I described above](https://github.com/greasemonkey/greasemonkey/issues/1849#issuecomment-77989156).

**Comment by ngyikp** [comment] 2015-04-28 15:37
Sorry for the late reply, I almost forgot about this issue.

Taking a look at the userscript you linked, you probably need to ```@grant unsafeWindow```, or in fact, I use ```window.MutationObserver``` and it works fine on my user script. If it still doesn't work, then I'm not sure why :/

**Comment by meitar** [comment] 2015-04-30 18:27
> Taking a look at the userscript you linked, you probably need to @grant unsafeWindow, or in fact, I use window.MutationObserver and it works fine on my user script. If it still doesn't work, then I'm not sure why :/

This was it. I changed the reference from `unsafeWindow.MutationObserver` to `window.MutationObserver` and everything worked without incident. I didn't even need to `@grant` anything new. Thank you very much!

**Comment by kekkc** [comment] 2015-05-30 10:37
Hm, issue is open since 2 years and still present in 3.2. One year ago Ventero already posted a patch and solution:
https://github.com/greasemonkey/greasemonkey/issues/1849#issuecomment-39640607

Why is this not implemented? With every new GM version I can edit it manually, otherwise I have no possibility to be sure to execute sth. before anything else has loaded.

@arantius It would be great if there's an explanation or info if this will ever be fixed.

**Comment by janekptacijarabaci** [comment] 2015-05-31 08:40
I've pushed a fix to the testing branch: https://github.com/greasemonkey/greasemonkey/compare/master...janekptacijarabaci:_testBranch_earlierScriptRuns_aboutBlank_documentStart

**Comment by arantius** [comment] 2015-05-31 12:40
But there's no content in `about:blank`.  What's the point of adding more code to discern start from end?  What's the practical benefit?

**Comment by janekptacijarabaci** [comment] 2015-05-31 13:19
Because of time sequence (document-start: it will always be before document-end).

Btw (about:blank, document.documentElement.outerHTML):

DOMWindowCreated:
``` <html><head></head></html> ```

DOMContentLoaded:
``` <html><head></head><body></body></html> ```

But it's just a suggestion. It is entirely up to your discretion :-)

**Comment by arantius** [comment] 2015-05-31 13:21
I absolutely want to fix bugs, if there's real bugs here.  But this report is very winding and confusing.  I've very much lost the plot.

I have no idea why about:blank is even in context?  What does it have to do with the original report?  Is there a particular bug you can explain, which this is the solution to?  Should there be an issue specifically for that?

**Comment by janekptacijarabaci** [comment] 2015-05-31 13:34
I just combined the two things. There's nothing more to it.
Ad https://github.com/greasemonkey/greasemonkey/issues/2041

**Comment by arantius** [comment] 2015-05-31 17:09
Tentatively putting into the next release milestone, to hopefully figure out what this issue report really means.  Then either fix or defer depending on complexity.

**Comment by janekptacijarabaci** [comment] 2015-06-05 12:14
Ad https://github.com/greasemonkey/greasemonkey/issues/1849#issuecomment-32128290

The difference can be seen here:
https://gist.github.com/janekptacijarabaci/30f7f2363b1fd555c5b1

**Comment by arantius** [comment] 2015-07-31 14:25
First, to confirm @Ventero's first comment: https://gist.github.com/arantius/77d8a42fc3bd3a30972b

One script, based on that in the original description.  Two HTML pages, which differ only by the relative placement of their title and script nodes.  When I open `mut1.html` I see:

    user script mutation observer setup ... 
    <head>
    <meta charset="utf-8">
    <title>Mutation Event Test Page 1</title>
    <script>console.log('content of Mutation Event Test Page 1');</script></head>
    content of Mutation Event Test Page 1
    
Only, but when I open `mut2.html`, I see:

    user script mutation observer setup ...
    <head>
    <meta charset="utf-8">
    <script>console.log('content of Mutation Event Test Page 2');</script></head>
    content of Mutation Event Test Page 2
    Yes, script is active! Hurray!

While `mut3.html` logs just:

    user script mutation observer setup ...
    <head>
    <meta charset="utf-8">
    <title>Mutation Event Test Page 2</title>
    </head>
    <body></body>

So the issue is that `document-start` does not happen when we want.  Rather than "immediately after the root element of a document has been created" like the documentation says, it's actually "immediately after the first script node is added (but before it is executed, or any node is added to the body, whichever comes first".

In the case that the first script/first body node comes after the title node, there is no "title added" mutation event, because the title is already in the document.  Back when `document-element-inserted` was selected, it was done intentionally, because it was observed that this point is late enough that the document does exist, and thus (e.g.) `<style>` nodes can easily be attached.

There are [other observer events](https://developer.mozilla.org/de/docs/Observer_Notifications#Documents).  As mentioned above, `content-document-global-created` might seem promising at first.  If I edit GM to use that instead of `document-element-inserted` (and tweak the observer to handle that event's different semantics), the script fails with `document.documentElement is null`.  So remove that reference from the script and then it works as expected, all three mutation observers fire.

**But** critically e.g. this script:

    ﻿// ==UserScript==
    // @name        Reddener
    // @version     1
    // @include     *
    // @grant       GM_addStyle
    // @run-at      document-start
    // ==/UserScript==
    
    console.log('Reddening ...');
    try {
      GM_addStyle('* { color: red; }');
    } catch (e) {
      console.error(e);
    }
    
Fails, `GM_addStyle` does not work, because it expects to be able to modify the nonexistent document.  So such a change improves one use of the feature and degrades another.

**Comment by arantius** [comment] 2015-07-31 14:54
https://bugzilla.mozilla.org/show_bug.cgi?id=1189770

**Comment by the8472** [comment] 2015-08-20 21:48
How about adding a new option based on `DOMWindowCreated` or `content-document-global-created`? Those who need their scripts to run really early can do so but must code defensively since objects might be missing, everyone else can just wait for `document-start`.

**Closed** 2017-07-25 13:56 UTC
