### ISSUE TITLE
rename script issue in beta4

### ISSUE THREAD

**Issue by RazgrizHsu** [greasemonkey/greasemonkey#2730] opened 2017-11-25 03:16 UTC
Dear..

when you put the `@require` in script file,
you can't rename it

try create new one script put this into
```
// ==UserScript==
// @name     ChangeName
// @version  1
// @grant    GM.xmlHttpRequest
// @require  https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.js
// ==/UserScript==
```

**Comment by S-ed** [comment] 2017-11-25 05:33
Dupe of #2706

**Closed** 2017-11-28 19:43 UTC
Labels: duplicate
