### ISSUE TITLE
Request: add ArrayBuffer to GM_xmlhttpRequest

### ISSUE THREAD

**Issue by xkcpipxa** [greasemonkey/greasemonkey#2083] opened 2015-02-02 10:33 UTC
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data

Please add support for ArrayBuffer to GM_xmlhttpRequest

**Comment by janekptacijarabaci** [comment] 2015-03-19 10:03
Duplicate of bug #2045.

**Closed** 2015-03-20 16:16 UTC
