### ISSUE TITLE
How to avoid 'Script save error'

### ISSUE THREAD

**Issue by darkvier** [greasemonkey/greasemonkey#2847] opened 2018-02-13 23:28 UTC
I do not know if it happened to me alone, but currently it is impossible to work on the scripts since it always gives the error 'Script save error'

I only can save the script one time, the other times give me the error when save  and I need to close the browser and reopen it. Obviously this is a sh**...

Is there any way to prevent the error from occurring?

Windows 8.1 x64
FF 58.0.2 64bit
Greasemonkey 4.3beta4

**Comment by Sxderp** [comment] 2018-02-13 23:48
Hm. I think the editor was broken recently. Taking a quick look at the code, I don't see the "ScriptChange" message anymore.

**Comment by darkvier** [comment] 2018-02-14 00:52
Every time i press save after the first time, navigator console logs

> IndexedDB UnknownErr: ActorsParent.cpp:26569

**Comment by arantius** [comment] 2018-02-14 01:55
> Hm. I think the editor was broken recently.

WFM, 4.3beta4.  New script, edit in an alert, save, load a page, see alert.  (And edit again, see new alert.)

> I only can save the script one time, the other times give me the error when save

That's odd.  But not enough information to help.  https://wiki.greasespot.net/Greasemonkey_Manual:Getting_Help#What_to_Say

**Comment by Sxderp** [comment] 2018-02-14 02:12
> WFM

https://github.com/greasemonkey/greasemonkey/issues/2683#issuecomment-345393724

Same problem. "UserScriptChanged" is never sent (seems to have been removed?).

**Comment by Sxderp** [comment] 2018-02-14 02:15
Looks like it was removed here: https://github.com/greasemonkey/greasemonkey/commit/af15dc1718f6cf770fe93acd3e450041dd0adaaa#diff-c1cbd2d40a6f1515de1bc875df33136cL289

**Comment by Eselce** [comment] 2018-02-14 02:16
BTW: Someone else with this visual glitch of https://github.com/greasemonkey/greasemonkey/issues/2833#issuecomment-363304087...

**Comment by Sxderp** [comment] 2018-02-14 02:18
> BTW: Someone else with this visual glitch of ..

Was just thinking about this. I never had time to look into it over the weekend.

**Comment by darkvier** [comment] 2018-02-14 11:23
I just uninstalled the script and reinstalled it and it does not happen anymore.
Can it be related to having installed the script with a previous GM beta version and edit it with a newer one?

**Comment by Sxderp** [comment] 2018-02-14 13:03
@darkvier, It's likely the same problem as I mentioned earlier. If you force a transaction error you'll start getting the same error message again. This is a regression.

**Comment by darkvier** [comment] 2018-02-14 20:41
the bug has reappeared, I'm trying to find out the pattern by which it occurs

**Comment by Sxderp** [comment] 2018-02-14 20:53
@darkvier, if you follow the instructions in https://github.com/greasemonkey/greasemonkey/issues/2683#issuecomment-345393724 it'll appear.

The fix is known, it just needs to be written.

**Comment by arantius** [comment] 2018-02-27 22:09
Hopefully 973c9322a35c7e2c9fd69ba0325e3fcbf3c9ee04 will fix this.  I'll post when there's a beta build including this to test.

**Comment by Eselce** [comment] 2018-02-28 19:10
Can't reproduce the defect in https://github.com/greasemonkey/greasemonkey/issues/2683#issuecomment-345393724 with the current (inter-beta) version, so it seems to be fixed.

Apart from the editor not being updated immediately (name, @require tabs) and these messages:
 
```
<unavailable>  downloader.js:97
Error: Promised response from onMessage listener at @moz-extension://38f8bf13-ad38-4e21-850d-514be48e0341/src/bg/on-message.js:11:1 went out of scope  undefined
```

Additionally one message for every stored script each:

```
Could not execute user script [Greasemonkey Benutzerskript raw.githubusercontent.com/Wide Icon] 
 <unavailable>  execute.js:28
Could not execute user script [Greasemonkey Benutzerskript null/i18n test; Version 1] 
 <unavailable>  execute.js:28
Could not execute user script [Greasemonkey Benutzerskript raw.githubusercontent.com/Tall Icon] 
 <unavailable>  execute.js:28
Could not execute user script [Greasemonkey Benutzerskript null/Ball Icon; Version 1] 
 <unavailable>  execute.js:28
Could not execute user script [Greasemonkey Benutzerskript ncgamers.org/test] 
 <unavailable>  execute.js:28
```

**Comment by Sxderp** [comment] 2018-02-28 19:28
> Apart from the editor not being updated immediately (name, @require tabs) and these messages

But the resources get properly included and aren't lost on saves?

> Promised response from onMessage listener ... went out of scope  undefined

I think this might be from the silliness on how `onScriptInstall` is defined [1]. It's an async function that's simply awaiting on a promise. It can be simplified to a standard function that returns `installFromDownloader` (which is a promise because it's an async). Whether or not this is the actual issue, I dunno. 

[1] https://github.com/greasemonkey/greasemonkey/blob/master/src/bg/user-script-registry.js#L132

**Comment by Eselce** [comment] 2018-02-28 19:38
> But the resources get properly included and aren't lost on saves?

Yes, closing the editor and reopening it updated the data correctly (name, @require tab for jquery).

**Comment by Eselce** [comment] 2018-02-28 19:55
Hmm, btw, is there any use in this?

`async function() { return await promise; }`

Just wondering... It does exactly the same as

`async function() { return promise; }`

or (worse style) `function() { return promise; }`.

Either you take the promise as is (no change) or you wait for it with `await` (no change) or you use the return value/error state with `then`/`catch` (different promise, but same effect (*)).

(*) Oh, there's is a difference: `return await promise;` will do no error handling...

**Comment by Eselce** [comment] 2018-02-28 19:59
> It can be simplified to a standard function that returns ...

Ooops, you said it, so I agree...

**Comment by Sxderp** [comment] 2018-02-28 20:10
> or (worse style) `function() { return promise; }`

What do you mean worse style? If anything it would catch errors. By doing `async function` you're implicitly creating a promise. For example, if you have a bug in the code that doesn't actually return a promise. If you do `func().then()` you won't receive an error because it's valid. On the other hand if you don't declare it async and you do `func().then()` you'll get an error right away.

--

Also there's a problem with `installFromDownloader`. It uses an async function in the promise constructor.

https://github.com/greasemonkey/greasemonkey/blob/283a60c9a9f9853da9ae52466e855bf8dc2a27e5/src/bg/user-script-registry.js#L49-L51

You can't use an async function inside a promise constructor. The function is expected to run and return synchronously. Otherwise you'll likely to get silent errors or other weird behavior.

`installFromDownloader` should be adjusted to remove the `async` from the promise constructor and the `async` from the `txn.oncomplete`. In the `txn.oncomplete` resolve the userscript directly and add a `.then(saveUserScript).then(() => whatever`.

Furthermore, if `userscript.details` is resolved in `saveUserScript` then the whatever could be removed.

A similar change should probably be done to `loadUserScripts` in order to eliminate the `req.onsuccess = async event => {`.

**Comment by Eselce** [comment] 2018-02-28 20:18
>>  or (worse style) `function() { return promise; }`
>
> What do you mean worse style?

I like `async function() { return promise; }` better, because you can see immediately, that you get a `Promise`. If you don't return a `Promise`, you return automatically `Promise.resolve(value)` instead of `value`. When an exception occurs, you'll get a rejected `Promise`. Correct?

**Comment by Sxderp** [comment] 2018-02-28 20:22
> When an exception occurs, you'll get a rejected Promise. Correct?

Perhaps, but I think it's harder to debug. You may not get the exception until somewhere down the chain. The other option I could suggest is to comment above the function about it's async or promise returning nature. That way you get the benefit of "oh this should return a promise" and a "oh, I see right away it didn't return a promise" (when you get undefined error on the `.then` call).

**Comment by Eselce** [comment] 2018-02-28 20:28
Okay, the stronger argument is this one:

```
/* not async */ function f(b) {
  if (b) {
    return Promise.resolve(42);
  } else {
    return 4711;  // TYPO producing an error
}

f(true).then(val => console.log(val));
```

**Comment by Eselce** [comment] 2018-02-28 20:53
I see your point with exceptions, but at least, it will reach the `catch` at the end of the procedure... Whereas you sometimes get the exception caught, sometimes not (if not `async`). Normally, I use the returned promise, and as I learned now, even await is capable of forwarding the error state and value.
Thus the error code will not be lost, if you always use `async` and have a `catch` at the end of the chain...
```
(async function() {
  const ret = await new Promise((resolve, reject) => { throw "Fehler"; });
  return typeof ret;
})();

/*
Promise (rejected: Fehler)
*/
```

**Comment by arantius** [comment] 2018-03-07 15:20
At head now, trying to save the second script gives a notification which directly says "script with that name already exists", and leaves all edits in place.  If you reload at that point you go back to wherever the last (successful) save was.

**Closed by arantius** 2018-03-07 15:20 UTC

**Comment by arantius** [comment] 2018-03-07 17:23
All above fixes are in the latest nightly build ( https://arantius.com/misc/gm-nightly/greasemonkey-2018.03.07nightly.xpi ).  Please try it out and confirm whether they cover these issues.
