### ISSUE TITLE
Concept of safe CSP-bypassing API for inline scripts

### ISSUE THREAD

**Issue by lainverse** [greasemonkey/greasemonkey#2511] opened 2017-05-30 11:52 UTC
My idea is to add script-src with list of random 'nonce-...' values to each request with CSP. There should be as many nonces as scripts which require this API since they are one-time use only and multiple scripts can't use same nonce within same context.

Example:
```
...
// @grant GM_getNonce
...
var scr = document.createElement('script');
scr.setAttribute('nonce', GM_getNonce());
scr.textContent = 'console.log("test");';
document.body.appendChild(scr);
...
```

For each script with `@grant GM_getNonce` GM should generate unique random number per context where it runs with something like:
```
var array = new Uint32Array(numberOfScripts);
crypto.getRandomValues(array);
```
GM_getNonce() should return number assigned to a script in specific context.

This way we can have secure inline scripts without compromising existing security on the page since number will expire as soon as it will be used once. It could be a good idea to restrict this API to scripts with `@run-at document-start` only to make sure script author had enough time to inject his code before scripts on the page had chance to run.

Another way to implement this is to provide an API to register one or more sha256/sha512 hashes with something like: `// @CSPHashList  sha256-..., sha256-..., ...`
This way script authors will provide list of hashes of their scripts which they are going to inject into a page, but this won't let dynamic inline code and any change in existing code will require updating hash list.

**Comment by janekptacijarabaci** [comment] 2017-05-30 14:02
I suggest adding it as a comment #2046...

**Comment by lainverse** [comment] 2017-05-30 15:06
Ok, done.

**Comment by arantius** [comment] 2017-05-30 17:19
Indeed this is a dupe of #2046.

**Closed by arantius** 2017-05-30 17:19 UTC
Labels: duplicate
