### ISSUE TITLE
Fail when attemp to open images in some pages

### ISSUE THREAD

**Issue by Tagiru** [greasemonkey/greasemonkey#2565] opened 2017-09-16 22:56 UTC
Firefox 55.0.3
Greasemonkey 3.11/3.12beta1
AAK-Cont Userscript For uBlock Orgin
Adsbypasser Lite

In certain pages like wikia or for easy example this page https://sharewareonsale.com/s/covert-pro-giveaway-coupon-sale , when i click in the box covert image to enlarge it this doesn't display... even if i trying to open it in another tab https://sos.azadicdn.com/wp-content/uploads/2016/06/box_covert_pro_AE_611x686-1.png?6000 
I tested deactivating one by one user scripts and doesn't work until i disable all of them...then loads normally. I tested in other userscript managers like tampermonkey or violentmonkey, and this doesn't happen... and is supposed that Greasemonkey is the unique 100% compatible in firefox platform... so that I will be grateful if you fix this annoying issue, thank you. im so sorry if i dont express myself correcly, im still learning this amazing language

**Comment by Sxderp** [comment] 2017-09-16 23:22
Dupe of #2524. This is probably not going to get fixed in the 3.x branch. I believe the focus is on porting to WebExtensions.

**Comment by arantius** [comment] 2017-09-16 23:35
Correct on both counts @Sxderp .

**Closed by arantius** 2017-09-16 23:35 UTC
