### ISSUE TITLE
Userscript settings window is too large.

### ISSUE THREAD

**Issue by onedude9000** [greasemonkey/greasemonkey#2214] opened 2015-07-02 15:48 UTC
Hello everyone.
I use a larger fonts size (125%) - it is standard windows 7 settings but because of this "userscript settings" window is too large and "edit script" button hidden beyond the screen border.

This only happens with a 1600x900 screen resolution and more than 125% font size.
For example with a 1920x1080 screen resolution and 125% font size "edit script" button still on the screen.

How do I make "userscript settings" window a little smaller? It is very inconvenient to change the screen resolution each time I want to edit the script.

Thanks.

**Comment by pyhedgehog** [comment] 2015-07-02 16:14
Duplicate of #2191.

**Closed** 2015-07-02 16:23 UTC
