### ISSUE TITLE
FF 36.0 breaks GM_listValues()

### ISSUE THREAD

**Issue by erosman** [greasemonkey/greasemonkey#2093] opened 2015-02-27 10:51 UTC
An hour ago, after FF 36.0 upgrade I noticed the following error:

> Error: Permission denied to access property 'length'

Corresponding code:

    var keys = GM_listValues();  
    for (var i = 10, len = keys.length; i < len; i++) { }

More:
> Error: Permission denied to access object

Corresponding code:

    for (var i in GM_listValues()) { }

**Comment by GM-Script-Writer-62850** [comment] 2015-02-28 00:12
I can confirm this on ff 38 a2

**Comment by rotemdan** [comment] 2015-02-28 15:53
Confirmed on FF 36.0/Windows 7 (breaks one of my personal scripts).

Output of `console.log(GM_listValues())` seems to be correct though. It is only when the `length` property is accessed or a specific index such as `GM_listValues()[0]` that the exception is thrown.

**Comment by GM-Script-Writer-62850** [comment] 2015-02-28 15:59
i am unable to convert it to a string
`alert(GM_listValues())`
`GM_listValues().soString()`

**Comment by arantius** [comment] 2015-02-28 16:13
To anyone experiencing this, it would be valuable to know: is Greasemonkey 3.0beta1 better, worse, or the same in this regard?

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/?page=1#version-3.0beta1

**Comment by GM-Script-Writer-62850** [comment] 2015-02-28 16:20
i rewrote my script to avoid using this function, but let me test it
`alert(GM_listValues())` works
`alert(GM_listValues()[0])` works
using firefox developer 38.0a2

**Comment by arantius** [comment] 2015-02-28 16:21
You mean, for `alert(GM_listValues())`: GM 2.3 works, 3.0beta1 works.  And for `alert(GM_listValues()[0])`: GM 2.3 fails, 3.0beta1 works?

**Comment by GM-Script-Writer-62850** [comment] 2015-02-28 16:44
alert(GM_listValues()[0]) fails in 2.3 but works in 3.0b1
appears to be fully functional in GM 3.0b1 in ff 38a2
completely fails in GM 2.3 in ff 38a2

**Comment by TimidScript** [comment] 2015-02-28 18:00
@GM-Script-Writer-62850

Does <code>GM_listValues().length</code> work?

**Comment by erosman** [comment] 2015-02-28 18:40
Is there any alternative to GM_listValues() for deleting all values?

**Comment by ArkadiuszMichalski** [comment] 2015-02-28 18:54
Firefox 36, Win 7 64bit, GM 2.3 and have the same problem. Some test:
alert(GM_listValues), alert(GM_listValues()), alert(GM_setValue) and similar >> Permission denied to access property 'toString'

alert(GM_listValues()[0]), console.log(GM_listValues()[0]) >> Permission denied to access property '0'

console.log(GM_listValues) , console.log(GM_listValues()) << this works correct

**Comment by rotemdan** [comment] 2015-02-28 19:08
Upgraded from 2.3 to 3.0b1 (FF36, Win7 64Bit) and now the problem seems to be resolved. Seems to work correctly, as far as I can tell (my script makes extensive use `GM_listValues()`, `GM_getValue()` and `GM_setValue()`, and currently stores more than 24,000 elements at one instance - totaling at about 300Kb-500Kb of storage).

It would be useful to either issue a fix for the older 2.x branch or to quickly promote the beta to a stable release, since the vast majority of end-users would still be using the older version.

**Comment by arantius** [comment] 2015-02-28 19:12
The intended changes for 3.0 didn't address this on purpose, they just happened to be widespread for what was targeted.  Almost everything got rewritten.  I don't know why the current one is broken or why the new one helps.

And I'm still worried that there's other bugs left in 3.0.  But that is valuable information and may indeed prompt the 3.0 release to be hastened.  I don't know how much effort a targeted fix for this would be yet.

**Comment by rotemdan** [comment] 2015-02-28 20:00
I agree hasting to a new, less-tested version wouldn't necessarily be the wisest choice, so I'll try to do my best to help:

I'm not really in a position to run the extension directly from the code right now (I'll try to figure out how to do that, hopefully it isn't that hard). But it might be useful just to try and clone the repository at previous states and see when exactly did the problem got resolved. For example, an obvious candidate would checking its state before and after this commit: 283259740e0405b81627d58ce4e5667f10509b69, or the one preceding it. Since it doesn't really require a deep (or any) understanding of the code (- though that is always helpful) I'll try to do that if I find the time.

**Comment by rotemdan** [comment] 2015-02-28 21:48
Alright, I cloned the repository before and after 283259740e0405b81627d58ce4e5667f10509b69 and built it (had to install Cygwin since I'm a windows user).

I used the following test script: 

```js
// ==UserScript==
// @name       Storage test
// @description Test Greasemonkey storage
// @match      https://www.google.com*
// @version     0.1

// @grant          GM_getValue
// @grant          GM_setValue
// @grant          GM_deleteValue
// @grant          GM_listValues
// ==/UserScript==

console.log("Starting storage test");

GM_setValue("TestKey1", "TestValue1");
GM_setValue("TestKey2", "TestValue2");
console.log("GM_getValue: " + GM_getValue("TestKey1"));
console.log("GM_listValues: " + GM_listValues());
console.log("GM_listValues().length: " + GM_listValues().length);
console.log("GM_listValues()[0]: " + GM_listValues()[0]);

GM_deleteValue("TestKey1");

console.log("GM_getValue: " + GM_getValue("TestKey1"));
console.log("GM_listValues: " + GM_listValues());
console.log("GM_listValues().length: " + GM_listValues().length);
console.log("GM_listValues()[0]: " + GM_listValues()[0]);
```


Result of code state before commit 283259740e0405b81627d58ce4e5667f10509b69 (FF36 Win7 64Bit):
```
"Starting storage test"
"GM_getValue: TestValue1"
Permission denied to access property 'valueOf'
```

Result of code state after commit 283259740e0405b81627d58ce4e5667f10509b69 (FF36 Win7 64Bit):
```
"Starting storage test"
"GM_getValue: TestValue1"
"GM_listValues: TestKey1,TestKey2"
"GM_listValues().length: 2"
"GM_listValues()[0]: TestKey1"
"GM_getValue: undefined"
"GM_listValues: TestKey2"
"GM_listValues().length: 1"
"GM_listValues()[0]: TestKey2"
```

Note that it doesn't necessarily mean that the one specific commit I tested was the only one responsible for the fix, it might have resulted from a series of code changes. I can't really tell because I'm not really familiar with the code.

**Comment by tobias-engelmann** [comment] 2015-03-04 10:34
To me it seems to be related to #2033 so that Mozilla moved on from showing a warning to blocking the access completely.

**Comment by erosman** [comment] 2015-03-04 11:18
I previously (2015-01-17) pointed out issues about GM_listValues in [https://bugzilla.mozilla.org/show_bug.cgi?id=1048164](https://bugzilla.mozilla.org/show_bug.cgi?id=1048164)

**Comment by arantius** [comment] 2015-03-13 15:38
I just updated my tester ( https://gist.github.com/arantius/1157543 ) to check this, and it now logs:

    GM_listValues() works: i,j
    There are 2 values.
    GM_deleteValue() works (if "j" does not show up):
    GM_listValues() works: i
    There are 1 values.
    
It works.  I'm moving forward with 3.0 as the implicit fix to this.

**Closed by arantius** 2015-03-13 15:38 UTC
