### ISSUE TITLE
Document FF sync requirements

### ISSUE THREAD

**Issue by nexushoratio** [greasemonkey/greasemonkey#2440] opened 2016-10-16 01:47 UTC
I just spent a couple of hours trying to understand why my scripts were not syncing.

I finally came across this comment https://github.com/greasemonkey/greasemonkey/issues/2351#issuecomment-211538042 
"""
There's a very strict limit to the number of bytes in Sync data (on Mozilla's servers, at least), so such a feature would not "work", general case. You need to solve this yourself.
"""

That was in reference to not being able to sync the body of a script (that is, one you installed locally).

It would be nice if this was more prominently documented somewhere.

(Also, I'm not sure how to tell if a script is installed via file:// or not; but I assume that if it's not syncing, that's how I installed it)

**Comment by nexushoratio** [comment] 2016-10-16 05:15
Oh, and did find this:

gm_scripts/config.xml

Which lists the installurl and downloadurl .

I suppose that would be nifty to expose through the UI.

**Comment by janekptacijarabaci** [comment] 2016-10-16 05:49
> Which lists the installurl and downloadurl .
> I suppose that would be nifty to expose through the UI.

Dupe of #2363

**Closed** 2017-07-25 14:00 UTC
