### ISSUE TITLE
Problem with Sync

### ISSUE THREAD

**Issue by mikhoul** [greasemonkey/greasemonkey#2335] opened 2015-11-15 02:04 UTC
I use Greasemonkey on my 2 computers and for years Greasemonkey sync was fine. Today I openned my laptop with Firefox and I was waiting for everythings to sync (Userscrips, Userstyles and Addons) everythings synced fine except Greasmonkey (Userscripts).

I had the latest release version, so I said to myself I will try the beta realese but sadly the same thing happen no sync for my UserScripts  ::disappointed::

I looked for a forum but there was a guy with the same problem  since the end of October and there was no answers.

So I'm here to know if it is a real bug or if something in my settings of the greasemonkey addon could have become corrupt and prevent the sync of my Userscripts ::grey_question:: ::grey_question::

If the problem is on my side tell me what setting I should reset to restart the sync.

The 2 computers are on Firefox 42 with Win 7,

Regards !

**Comment by janekptacijarabaci** [comment] 2015-11-15 06:06
See also:
https://groups.google.com/forum/#!topic/greasemonkey-users/2uXRQal8NTo
https://github.com/greasemonkey/greasemonkey/issues/2287

**Comment by mikhoul** [comment] 2015-11-15 18:26
Thanks @janekptacijarabaci for the information ::ok_hand::

I did not see them last night I was looking only in the opened issues.

@arantius   Here's my sync logs from my 2 computers, maybe with the laptop log you will be able to see where it begun. If you need any other informations or testing an Alpha just ask me, I will be happy to help you to track the bug.

Logs ---> https://mega.nz/#!ssQzgAJQ!AxyL6_Oi7X8_yv99vhttJ0BOjEEja7ER8Y09VYAbFec

**Comment by alexolog** [comment] 2015-11-20 05:39
Same error here as well, scripts not syncing.

**Comment by mikhoul** [comment] 2015-11-20 16:01
@janekptacijarabaci  @arantius   Why the bug is closed  ::question::

**Comment by arantius** [comment] 2015-11-20 16:13
Why do you think the bug is closed?  It's not.  A bug which was referenced is closed.

**Comment by arantius** [comment] 2015-11-20 16:20
I can seem to confirm, kinda.  Things *seem* wrong sometimes on my day-to-day profile.  Test profiles are 100% definitely installing and removing scripts when I press the "sync now" button.  And my day-to-day profile produces no (error) logs at all.

Logs might help, but putting them in https://gist.github.com/ makes them easier to read.

**Comment by mikhoul** [comment] 2015-11-20 20:30
> Why do you think the bug is closed? It's not. A bug which was referenced is closed.

If I was knowing I would not have asked ::grey_exclamation::

So what is the solution ? I don't understand. All my other things (UserStyles, Addblock Filters, addons, bookmarks CTR prefs) sync perfectly exept Greasemonkey, 

What can I do @arantius  in a pratical way to make UserScripts sync too ? 

Regards.

**Comment by jerone** [comment] 2015-12-13 16:21
I'm probably having the same issue here too. I have two Firefox setups with "work" having the latest version of GreaseMonkey and my "home" setup having the beta version installed. On my home setup I installed some scripts a few days (maybe over a week) ago that aren't synced over to work. I double checked that the not-synced scripts aren't edited and the install url is still valid.

Any information I can provide?

**Comment by jerone** [comment] 2015-12-13 16:47
After opening `about:sync-log` on my "work" setup (where some files where missing), I noticed the following message:
```
1449475348092	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: https://github.com/MichaelSp/github-issue-votes.user.js/GitHub: Issue Votes@greasespot.net
1449475348092	Sync.AddonsReconciler	DEBUG	Adding change because add-on not present locally: https://github.com/MichaelSp/github-issue-votes.user.js/GitHub: Issue Votes@greasespot.net
1449475348092	Sync.AddonsReconciler	INFO	Change recorded for https://github.com/MichaelSp/github-issue-votes.user.js/GitHub: Issue Votes@greasespot.net
1449475348092	Sync.Tracker.Addons	DEBUG	changeListener invoked: 1 https://github.com/MichaelSp/github-issue-votes.user.js/GitHub: Issue Votes@greasespot.net
1449475348092	Sync.Store.Addons	DEBUG	https://github.com/MichaelSp/github-issue-votes.user.js/GitHub: Issue Votes@greasespot.net not syncable: type not in whitelist: greasemonkey-user-script
1449475348092	Sync.Tracker.Addons	DEBUG	Ignoring change because add-on isn't syncable: https://github.com/MichaelSp/github-issue-votes.user.js/GitHub: Issue Votes@greasespot.net
```

Last two lines are interesting...

**Comment by mikhoul** [comment] 2015-12-13 19:49
@jerone Nobody here seem interested provide a fix or tell how to do to have the sync working. :cry:

**Comment by jerone** [comment] 2015-12-13 20:36
Let's provide as much information as possible.

**Comment by janekptacijarabaci** [comment] 2015-12-13 22:40
Can you try this:

Ad https://github.com/greasemonkey/greasemonkey/blob/3.6/modules/sync.js#L87

From:
``` javascript
ScriptStore.prototype = {
  __proto__: gWeave.Store.prototype,

  changeItemID: function(aOldId, aNewId) {
```

To:
``` javascript
ScriptStore.prototype = {
  __proto__: gWeave.Store.prototype,

  _syncableTypes: ["greasemonkey-user-script"],

  changeItemID: function(aOldId, aNewId) {
```

**Comment by arantius** [comment] 2015-12-14 03:21
That looks like a fair idea, but it's AddonsEngine that checks this ( http://mxr.mozilla.org/mozilla-central/source/services/sync/modules/engines/addons.js#536 ), not AddonStore.

Or at least it is now?  Or is it both?  We try to override this already ( https://github.com/greasemonkey/greasemonkey/blob/master/modules/sync.js#L185 ) perhaps we just need it in both the Store and the Engine.

**Comment by thakyZ** [comment] 2016-01-29 23:49
I would just like to inquire, what is the status on fixing this issue?

**Comment by emanresusername** [comment] 2016-02-23 07:28
:+1:

**Comment by paintedsky** [comment] 2016-02-24 18:34
Agree that this feature not working is super frustrating for sync users. Any chance to bump this up in priority?

**Comment by mikhoul** [comment] 2016-02-24 21:10
:point_up:

**Comment by arantius** [comment] 2016-03-04 16:52
This is just a hard bug to work on, because it's hard to reproduce and thus hard to diagnose.

Good-ish news, I see an interesting symptom, based on trial-and-error diagnostics.  I can observe the value of `gWeave.Status.ready` go from false to true several seconds after launching Firefox.  But the `weave:service:ready` observer never fires, and without that our Sync mechanisms never get hooked up.

Manually polling that boolean is probably a servicable, if cruddy, workaround.

**Comment by paintedsky** [comment] 2016-03-04 17:03
Glad you're seeing some progress in nailing this down- thanks for your hard work @arantius :)

**Comment by arantius** [comment] 2016-03-04 17:22
This issue should be fixed in version 3.8beta2.  If you're experiencing this problem, please: 1) confirm you're still experiencing it, 2) describe how you confirmed that, 3) install 3.8beta2, 4) check whether it's fixed, 5) describe whether it's fixed or not, and how you know that.

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/?page=1#version-3.8beta2

**Comment by yurikhan** [comment] 2016-03-04 17:43
1: I might have this problem. (It’s hard to understand what exactly *this* problem is.)

2: I know I have *a* problem with Sync because I have Firefox with Greasemonkey at home and at work. They sync bookmarks and Stylish userstyles, but not Greasemonkey scripts. The option in Greasemonkey preferences is set on both instances.

3: I am now installing 3.8beta2 on both systems. Results after restart.

**Comment by arantius** [comment] 2016-08-02 13:48
Nobody replied to confirm or disclaim the fix, bumping out of this release milestone.

(Please do reply if you have any relevant feedback.)

**Comment by renyouguo** [comment] 2016-08-02 13:51
fixed

**Closed** 2016-08-02 14:25 UTC
