### ISSUE TITLE
Single quote in script name breaks the user script

### ISSUE THREAD

**Issue by LMLB** [greasemonkey/greasemonkey#3035] opened 2019-05-09 20:11 UTC
https://github.com/greasemonkey/greasemonkey/blob/6829e4d721d25759ff81396d28274e8eac6fa1b1/src/user-script-obj.js#L333
`this.toString()` is inserted without escaping the `\` and `'` characters.

Example that reproduces the issue:
```js
// ==UserScript==
// @name Single quote ' test
// @include *
// ==/UserScript==
console.log('Single quote test');
```

**Comment by Cerberus-tm** [comment] 2019-05-11 21:38
I have experienced this bug too. And it must be new, because all of a sudden one of my userscripts gave a mysterious error in the browser console and just failed to execute altogether. It had been functioning perfectly since forever.

@LMLB So it was very hard for me to locate this error. How did you do it?

**Comment by StigNygaard** [comment] 2019-05-17 10:09
Confirmed. But there's more to the problem.

I have several userscripts named something like "Stig's scriptname". Some of them was working, but one wasn't working for me. The one that wasn't working didn't seem to be activate at all. I couldn't get it to write anything in the log.

After some experiments including turning scripts on and off (and seeing this issue), I have come to the conclusion:

1) If script is already installed, enabled and working, it will continue to work if you don't mess around with it (Maybe until it is updated?).
2) If you disable a script, you cannot get it working again be re-enabling it :-( It seems to be permanently disabled even though status says it is enabled.

Me to think it must be a recent problem, probably caused by latest Greasemonkey update.

**Comment by AltoRetrato** [comment] 2019-05-28 01:25
I've met this issue as well. Hoping that a new release will fix this soon!

**Comment by StigNygaard** [comment] 2019-06-02 07:23
Hi @arantius 
Assuming @badbrainz 's commit fixes this problem, what is the ETA of a new Greasemonkey release? Will we wait for other stuff before releasing a new version? Yes, I'm a bit [impatient](https://community.metabrainz.org/t/how-can-i-get-high-res-cover-art-from-cd-baby/388315/7?u=stignygaard) ...

**Comment by arantius** [comment] 2019-06-12 16:44
Manually merged the PR with an additional fix.

**Closed by arantius** 2019-06-12 16:44 UTC

**Comment by StigNygaard** [comment] 2019-06-12 18:17
And all seems normal again in 4.9. Thanks :-)
