### ISSUE TITLE
GM_openInTab does not create child tab in TreeStyle Tabs

### ISSUE THREAD

**Issue by haarp** [greasemonkey/greasemonkey#2087] opened 2015-02-08 12:11 UTC
When TreeStyle Tabs (https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) is used, opening a new tab "B" from tab "A" will result in B being a child of A. TST creates a hierarchical structure of openened tabs. This seems to work fairly well, however:

When Greasemonkey's GM_openInTab is used, tab B ends up being separate and not a child of tab A, as it ought to be.

**Comment by janekptacijarabaci** [comment] 2015-02-08 12:21
Dupe of https://github.com/greasemonkey/greasemonkey/issues/2055

**Closed** 2015-02-08 16:08 UTC
