### ISSUE TITLE
Two install dialogs when drag drop or loading bookmark

### ISSUE THREAD

**Issue by cmasc** [greasemonkey/greasemonkey#2395] opened 2016-05-03 04:30 UTC
GM 3.8
FF 46

**Comment by janekptacijarabaci** [comment] 2016-05-03 05:17
Dupe of https://github.com/greasemonkey/greasemonkey/issues/2292#issuecomment-143562376

It's been fixed (FF 47.0beta1).

**Closed** 2016-08-02 14:19 UTC
Labels: duplicate
