### ISSUE TITLE
TypeError: GM_util.openInEditor is not a function

### ISSUE THREAD

**Issue by vsemozhetbyt** [greasemonkey/greasemonkey#2288] opened 2015-09-24 12:28 UTC
GM Version 3.4.1 on Firefox Nightly 44.0a1 (2015-09-23)

On attempt to edit a script I get this error in the browser console

`TypeError: GM_util.openInEditor is not a function  scriptprefs.xul:1:1`
   `oncommand()  scriptprefs.xul:1`
   `cmd_showItemPreferences_doCommand()  extensions.js:1112`
   `gVC_doCommand()  extensions.js:1435`
   `showPreferences()  extensions.xml:1564`
   `oncommand()  about:addons:1`

**Comment by vsemozhetbyt** [comment] 2015-09-24 12:34
GM Version 3.5beta1 on the same Firefox — it is OK.

**Comment by arantius** [comment] 2015-09-24 13:17
Dupe of #2285 .

**Closed by arantius** 2015-09-24 13:17 UTC
