### ISSUE TITLE
GM_listValueot work on firefox 35 anymore

### ISSUE THREAD

**Issue by deltamarkus** [greasemonkey/greasemonkey#2076] opened 2015-01-22 19:58 UTC
Hello GM_listValue don't work anymore
but someone has an fix for greasymonkey 
see this link  https://greasyfork.org/de/forum/discussion/2918/issue-with-gm-getvalue-from-gm-listvalues-array-in-firefox#latest
please update the greasemonkey version

thank you

**Comment by arantius** [comment] 2015-01-23 15:01
Dupe of #2033.

**Closed by arantius** 2015-01-23 15:01 UTC
