### ISSUE TITLE
User Script Preferences Dialog window is too tall

### ISSUE THREAD

**Issue by Imold** [greasemonkey/greasemonkey#2218] opened 2015-07-10 17:35 UTC
The addition of Matched Pages (witch I can not find any documentation on) has made the User Script Preferences Dialog window taller then the max resolution of my screen (1366 x 768). As I can not find any documentation on Matched Pages I just went into the xpi file and deleted it. However if this is something that is here to stay then the User Script Preferences Dialog window must be made short enough to fit on my screen (again my max resolution is 1366 x 768).

**Comment by ngyikp** [comment] 2015-07-10 17:43
Duplicate of #2191 

The Matched Pages section is introduced on https://github.com/greasemonkey/greasemonkey/pull/2126 and allows editing of ``@match`` fields that is found on some userscripts, it is similar to ``@include`` but it is parsed more strictly.

**Comment by janekptacijarabaci** [comment] 2015-07-10 17:45
The documentation is here: http://wiki.greasespot.net/Metadata_Block#.40match

**Closed** 2015-07-10 17:46 UTC
