### ISSUE TITLE
[WINDOWS ONLY?] Source url is replaced by file:///tmp/* when installing from "Show sript source"

### ISSUE THREAD

**Issue by gwarser** [greasemonkey/greasemonkey#2348] opened 2016-01-06 18:54 UTC
User scripts may be installed by clicking on "install" button in "Greasemonkey installation" window or by clicking "Show script source" and then "Install script".
When using first way all is ok.
When using second way, script url is changed to `file:///tmp/gm-temp/script-name` and: 
 * When `@namespace` is missing, script will be installed second time. [example](https://github.com/anonim1133/wykop-userjs/blob/a86014414395f71e2b9f930cf8ec876374808c24/wykop-zawijas.user.js)
 * When `@namespace` is present, but `@updateURL` is missing, previously installed script may be overwritten with wrong metadata - wrong update URL pointing to `file:///tmp/gm-temp/script-name` [example](https://greasyfork.org/en/scripts/1993-notatkowator-2000)

Linux Mint 17.2, Firefox 45a2, Greasemonkey 3.6.

**Comment by janekptacijarabaci** [comment] 2016-01-06 23:01
AFAIK: This is how it works.

file://[anything] (copying *.user.js files by using (e.g.) the drag-and-drop method) => "Show script source" and then "Install script". The result will be the same (@updateURL=file:///tmp/gm-temp/script-name).

**Comment by arantius** [comment] 2016-01-07 03:27
Showing the temp file is an intentional security feature: so the site cannot possibly play tricks by serving (e.g.) a different script to the request for the one that can be installed vs. the one that can be viewed.  Download first, then display if requested.

Looks like the rest is a bug caused by not remembering the original URL.

**Comment by janekptacijarabaci** [comment] 2016-01-07 13:10
I've pushed a fix to the testing branch:
https://github.com/janekptacijarabaci/greasemonkey/tree/_testBranch_showSriptSource_sourceUrl
...but:

Ad https://github.com/janekptacijarabaci/greasemonkey/commit/e9baf2695d66c5d9900eaa43d796fd63ea2f40e2#diff-fca536fb25de50f4f011771aa1a74483R498
This message (notificationBox) is automatically closed after page load (confirmed on FF 31+, not confirmed on FF 30-). I don't know what's bug...

**Comment by arantius** [comment] 2016-01-20 20:39
This only reproduces with e10s on.

**Comment by arantius** [comment] 2016-01-20 21:15
This should be fixed in 3.7beta2: https://addons.mozilla.org/firefox/downloads/file/388504/greasemonkey-3.7beta2-fx.xpi?src=devhub

I'd appreciate confirmation either way.

**Comment by janekptacijarabaci** [comment] 2016-01-20 21:35
Also on e10s off.

AFAIK: Now it works strange...

1) The example:
https://github.com/anonim1133/wykop-userjs/blob/a86014414395f71e2b9f930cf8ec876374808c24/wykop-zawijas.user.js

`Raw` -> No notification bars

2) The example:
https://raw.githubusercontent.com/anonim1133/wykop-userjs/a86014414395f71e2b9f930cf8ec876374808c24/wykop-zawijas.user.js

`Show source code` -> Open the Install dialog (and the notification bar, but it soon disappears: see also https://github.com/greasemonkey/greasemonkey/pull/2350/files#diff-fca536fb25de50f4f011771aa1a74483R492)

**Comment by gwarser** [comment] 2016-01-21 12:44
On Greasyfork, middle clicking 'Install this script' button, opens two 'Greasemonkey Installation' windows.

**Comment by janekptacijarabaci** [comment] 2016-01-21 14:22
> On Greasyfork, middle clicking 'Install this script' button, opens two 'Greasemonkey Installation' windows.

Confirmed with e10s disabled.
...but not associated with a commit.

**Comment by arantius** [comment] 2016-01-21 14:29
Double install box: confirmed, but only with e10s disabled.

@janekptacijarabaci I can't confirm anything you said above, except the separate issue #2280.

**Comment by janekptacijarabaci** [comment] 2016-01-21 15:10
Not confirmed on:
Ubuntu 15.10
Firefox Nightly 46.0a1 (2016-01-21) x64
GM 3.7beta2

Confirmed on:
Windows 7
Firefox Nightly 46.0a1 (2016-01-20) x32
Firefox Nightly 46.0a1 (2016-01-21) x64
GM 3.7beta2

:-) ... :-/

**Comment by gwarser** [comment] 2016-01-21 17:08
Yes, this was on Fx 45 64b on Mint with e10s disabled (don't know why/when I disable it).
I also want to say, that I somehow installed two copies of script from github with URLs:
`https://github.com/anonim1133/wykop-userjs/raw/master/wykop-zawijas.user.js`
and with
`https://raw.githubusercontent.com/anonim1133/wykop-userjs/master/wykop-zawijas.user.js`
But I don't know how this happened and cannot reproduce.

**Comment by arantius** [comment] 2016-02-03 14:27
Back to the original issue (install URL when clicking show source).

With `Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0`, GM at e8d7643f56260441d6693878044317166d000f3d: NOT confirmed, both with e10s enabled and disabled.

And ugh, I meant to set up remote access to a Windows box today to be able to investigate that, but whoops, not accessible somehow.

**Comment by janekptacijarabaci** [comment] 2016-04-08 08:50
https://bugzilla.mozilla.org/show_bug.cgi?id=1263099

**Comment by arantius** [comment] 2016-04-18 18:33
I've merged the semi-related notification bar fix above, and can no longer reproduce this.  Closing for now, please reopen if you can still see this issue.

**Comment by arantius** [comment] 2016-04-18 18:34
No sorry, have not merged, but still don't see this error.

**Comment by janekptacijarabaci** [comment] 2016-04-18 18:47
The bug is always the same. I thought I wrote everything above already (only on Windows, the discussion on bugzilla - e.g. STR, screenshot with proof of bug).

Now I don't know what is left to do...

**Comment by janekptacijarabaci** [comment] 2016-04-18 18:51
> please reopen if you can still see this issue

I can not do it.

**Comment by janekptacijarabaci** [comment] 2016-04-18 19:10
Thanks for merged it.

**Comment by arantius** [comment] 2016-04-18 19:23
I keep missing the maybe windows only part.

**Comment by janekptacijarabaci** [comment] 2016-04-18 19:41
I personally don't know why it was reopened - it fixed the problem for me (https://github.com/greasemonkey/greasemonkey/commit/8e19516aec00ebfcbb5f7cbdb585452e0e340fe9).

I'm sorry, but I think it's a misunderstanding...

**Comment by arantius** [comment] 2016-04-19 01:38
Because I wanted to confirm on windows, and now I have, and I agree.

**Closed by arantius** 2016-04-19 01:38 UTC
