### ISSUE TITLE
unable to add new script

### ISSUE THREAD

**Issue by Gercho4** [greasemonkey/greasemonkey#2317] opened 2015-10-31 09:11 UTC
After installing the new version i see that the option for adding a new script is not working. I have 2 scripts added and I want to add a new one. When I click on new user script and  fill in the name, it tells me that a script with that name already exists it doesn't matter what I put as a name.

**Comment by janekptacijarabaci** [comment] 2015-10-31 10:36
Dupe of #2304
This is already fixed in the nightly: https://arantius.com/misc/gm-nightly/

**Closed** 2015-10-31 14:50 UTC
