### ISSUE TITLE
GM_xmlhttpRequest can't GET binary data in Firefox 39

### ISSUE THREAD

**Issue by trespassersW** [greasemonkey/greasemonkey#2228] opened 2015-07-29 10:18 UTC
<b>Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/39.0;
Greasemonkey 3.3</b>
When my script calls <code><pre>
GM_xmlhttpRequest({
	method: 'GET',
	url: URL,
    binary: true, 
    ...</code></pre>
Firefox 39 reports the error:
<pre>
greasemonkey-modules/content/xmlhttprequester.js line 182:
TypeError: req.sendAsBinary is not a function
</pre>

**Comment by janekptacijarabaci** [comment] 2015-07-29 10:33
Duplicate of #2221

**Closed** 2015-07-29 10:36 UTC
