### ISSUE TITLE
Greasemonkey 4.0/4.1 only runs userscripts at the top-level window

### ISSUE THREAD

**Issue by RyanHanekamp** [greasemonkey/greasemonkey#2767] opened 2017-12-13 18:54 UTC
I have a number of scripts that must run in <frame> and <iframe> windows, but Greasemonkeys 4.0 and 4.1 only run userscripts where window===window.top.

This is forcing me to install Violentmonkey to compensate for interior windows. This was a known workaround for me in 57+, but the 4.1 update also enabled and auto-updated my Firefox ESR 52 copy, which we use in production, and forced me to install the Violentmonkey workaround there as well.
Please fix. I have no interest in perpetually running multiple monkeys, and the 4.0+ GM async architecture is superior to the Violent/Tamper monkey varieties, so I don't want to revert.

**Comment by tobbexiv** [comment] 2017-12-13 19:20
Looks like a dupe of #2574 to me.

**Closed** 2017-12-13 20:57 UTC
Labels: duplicate

**Comment by makyen** [comment] 2017-12-13 21:13
While the title this is a dup, the text contains an issue that is not a dup of #2574 : the auto-"upgrade" to GM4 for FF version <57. I've opened a separate issue #2768 to cover this.
